# Load Dataset

In [3]:
from beir.datasets.data_loader import GenericDataLoader

data_path = "scifact"

corpus, queries, qrels = GenericDataLoader(
    data_path
).load(split="test")

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5183/5183 [00:00<00:00, 99684.87it/s]

In [5]:
import pandas as pd

corpus_df = pd.DataFrame.from_dict(
    corpus,
    orient="index"   
).reset_index()

In [6]:
corpus_df

,index,text,title
0,4983,Alterations of the architecture of cerebral wh...,Microstructural development of human newborn c...
1,5836,Myelodysplastic syndromes (MDS) are age-depend...,Induction of myelodysplasia by myeloid-derived...
2,7912,ID elements are short interspersed elements (S...,"BC1 RNA, the transcript from a master gene for..."
3,18670,DNA methylation plays an important role in bio...,The DNA Methylome of Human Peripheral Blood Mo...
4,19238,Two human Golli (for gene expressed in the oli...,The human myelin basic protein gene is include...
...,...,...,...
5178,195689316,BACKGROUND The main associations of body-mass ...,Body-mass index and cause-specific mortality i...
5179,195689757,A key aberrant biological difference between t...,Targeting metabolic remodeling in glioblastoma...
5180,196664003,A signaling pathway transmits information from...,Signaling architectures that transmit unidirec...
5181,198133135,AIMS Trabecular bone score (TBS) is a surrogat...,"Association between pre-diabetes, type 2 diabe..."
5182,198309074,Introduction: Among the inflammatory mediators...,Adhesion molecules and chemokines: relation to...

In [7]:
documents = [
    row['title'] + ". " + row['text'] 
    for _, row in corpus_df.iterrows()
]

# Embedding Model

In [8]:
from sentence_transformers import SentenceTransformer

In [9]:
embedding_model = SentenceTransformer("BAAI/bge-base-en-v1.5")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 2416.60it/s]

In [ ]:
import time

start_time = time.time()

corpus_embeddings = embedding_model.encode(
    documents,
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True
)

end_time = time.time()

print(f"Encoding took {end_time - start_time:.2f} seconds")
print(document_embeddings.shape)

import numpy as np

corpus_embeddings = np.load(
    "scifact_corpus_embeddings.npy"
)

In [11]:
corpus_df['embedding'] = list(corpus_embeddings)

# Faiss

In [12]:
import faiss

In [13]:
dimension = corpus_embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)
index.add(corpus_embeddings.astype('float32'))

In [14]:
index.ntotal

5183

In [15]:
queries

{'1': '0-dimensional biomaterials show inductive properties.',
 '3': '1,000 genomes project enables mapping of genetic sequence variation consisting of rare variants with larger penetrance effects than common variants.',
 '5': '1/2000 in UK have abnormal PrP positivity.',
 '13': '5% of perinatal mortality is due to low birth weight.',
 '36': 'A deficiency of vitamin B12 increases blood levels of homocysteine.',
 '42': 'A high microerythrocyte count raises vulnerability to severe anemia in homozygous alpha (+)- thalassemia trait subjects.',
 '48': 'A total of 1,000 people in the UK are asymptomatic carriers of vCJD infection.',
 '49': 'ADAR1 binds to Dicer to cleave pre-miRNA.',
 '50': 'AIRE is expressed in some skin tumors.',
 '51': 'ALDH1 expression is associated with better breast cancer outcomes.',
 '53': 'ALDH1 expression is associated with poorer prognosis in breast cancer.',
 '54': 'AMP-activated protein kinase (AMPK) activation increases inflammation-related fibrosis in the lungs.',
 '56': 'APOE4 expression in iPSC-derived neurons increases AlphaBeta production and tau phosphorylation causing GABA neuron degeneration.',
 '57': 'APOE4 expression in iPSC-derived neurons increases AlphaBeta production and tau phosphorylation, delaying GABA neuron degeneration.',
 '70': 'Activation of PPM1D suppresses p53 function.',
 '72': 'Activator-inhibitor pairs are provided dorsally by Admpchordin.',
 '75': 'Active H. pylori urease has a polymeric structure that compromises two subunits, UreA and UreB.',
 '94': 'Albendazole is used to treat lymphatic filariasis.',
 '99': 'Alizarin forms hydrogen bonds with residues involved in PGAM1 substrate binding.',
 '100': 'All hematopoietic stem cells segregate their chromosomes randomly.',
 '113': 'Angiotensin converting enzyme inhibitors are associated with increased risk for functional renal insufficiency.',
 '115': 'Anthrax spores can be disposed of easily after they are dispersed.',
 '118': 'Antibiotic induced alterations in the gut microbiome reduce resistance against Clostridium difficile',
 '124': 'Antiretroviral therapy reduces rates of tuberculosis across a broad range of CD4 strata.',
 '127': 'Arginine 90 in p150n is important for interaction with EB1.',
 '128': 'Arterioles have a larger lumen diameter than venules.',
 '129': 'Articles published in open access format are less likely to be cited than traditional journals.',
 '130': 'Articles published in open access format are more likely to be cited than traditional journals.',
 '132': 'Aspirin inhibits the production of PGE2.',
 '133': 'Assembly of invadopodia is triggered by focal generation of phosphatidylinositol-3,4-biphosphate and the activation of the nonreceptor tyrosine kinase Src.',
 '137': 'Asymptomatic visual impairment screening in elderly populations does not lead to improved vision.',
 '141': 'Auditory entrainment is strengthened when people see congruent visual and auditory information.',
 '142': 'Autologous transplantation of mesenchymal stem cells causes a higher rate of opportunistic infections than induction therapy with anti-interleukin-2 receptor antibodies.',
 '143': 'Autologous transplantation of mesenchymal stem cells causes fewer opportunistic infections than induction therapy with anti-interleukin-2 receptor antibodies.',
 '146': 'Autologous transplantation of mesenchymal stem cells has lower rates of rejection than induction therapy with anti-interleukin-2 receptor antibodies.',
 '148': 'Autophagy declines in aged organisms.',
 '163': 'Bariatric surgery has a positive impact on mental health.',
 '171': 'Basophils counteract disease development in patients with systemic lupus erythematosus (SLE).',
 '179': 'Birth-weight is positively associated with breast cancer.',
 '180': 'Blocking the interaction between TDP-43 and respiratory complex I proteins ND3 and ND6 leads to increased TDP-43-induced neuronal loss.',
 '183': 'Bone marrow cells contribute to adult macrophage compartments.',
 '185': 'Breast cancer development is determined exclusively by genetic factors.',
 '198': 'CCL19 is absent within dLNs.',
 '208': 'CHEK2 is not associated with breast cancer.',
 '212': 'CR is associated with higher methylation age.',
 '213': 'CRP is not predictive of postoperative mortality following Coronary Artery Bypass Graft (CABG) surgery.',
 '216': 'CX3CR1 on the Th2 cells impairs T cell survival',
 '217': 'CX3CR1 on the Th2 cells promotes T cell survival',
 '218': 'CX3CR1 on the Th2 cells promotes airway inflammation.',
 '219': 'CX3CR1 on the Th2 cells suppresses airway inflammation.',
 '230': 'Carriers of the alcohol aldehyde dehydrogenase deficiency mutation drink less that non-carries.',
 '232': 'Cataract and trachoma are the primary cause of blindness in Southern Sudan.',
 '233': 'Cell autonomous sex determination in somatic cells does not occur in Galliformes.',
 '236': 'Cell autonomous sex determination in somatic cells occurs in Passeriformes.',
 '237': 'Cells lacking clpC have a defect in sporulation efficiency in Bacillus subtilis.',
 '238': 'Cells undergoing methionine restriction may activate miRNAs.',
 '239': 'Cellular aging closely links to an older appearance.',
 '248': 'Chenodeosycholic acid treatment increases whole-body energy expenditure.',
 '249': 'Chenodeosycholic acid treatment reduces whole-body energy expenditure.',
 '261': 'Chronic aerobic exercise alters endothelial function, improving vasodilating mechanisms mediated by NO.',
 '268': 'Cold exposure increases BAT recruitment.',
 '269': 'Cold exposure reduces BAT recruitment.',
 '274': 'Combination nicotine replacement therapies with varenicline or bupropion lead to significantly higher long-term abstinence rates at 52 weeks than varenicline monotherapy.',
 '275': 'Combining phosphatidylinositide 3-kinase and MEK 1/2 inhibitors is effective at treating KRAS mutant tumors.',
 '279': "Commelina yellow mottle virus' (ComYMV) genome consists of 7489 baise pairs.",
 '294': 'Crossover hot spots are not found within gene promoters in Saccharomyces cerevisiae.',
 '295': 'Crosstalk between dendritic cells (DCs) and innate lymphoid cells (ILCs) is important in the regulation of intestinal homeostasis.',
 '298': 'Cytochrome c is released from the mitochondrial intermembrane space to cytosol during apoptosis.',
 '300': 'Cytosolic proteins bind to iron-responsive elements on mRNAs coding for DMT1. Cytosolic proteins bind to iron-responsive elements on mRNAs coding for proteins involved in iron uptake.',
 '303': 'DMRT1 is a sex-determining gene that is epigenetically regulated by the MHM region.',
 '312': 'De novo assembly of sequence data has more specific contigs than unassembled sequence data.',
 '314': 'Deamination of cytidine to uridine on the minus strand of viral DNA results in catastrophic G-to-A mutations in the viral genome.',
 '324': 'Deleting Raptor reduces G-CSF levels.',
 '327': 'Deletion of αvβ8 does not result in a spontaneous inflammatory phenotype.',
 '338': 'Dexamethasone decreases risk of postoperative bleeding.',
 '343': 'Diabetic patients with acute coronary syndrome experience increased short-term and long-term risk for bleeding events.',
 '350': 'Discrimination between the initiator and elongation tRNAs depends on the translation initiation factor IF3.',
 '354': 'Downregulation and mislocalization of Scribble prevents cell transformation and mammary tumorigenesis.',
 '362': 'During the primary early antibody response activated B cells migrate toward the inner-and outer paracortical areas where oxysterol accumulation is generated by stromal cells.',
 '380': 'Enhanced early production of inflammatory chemokines improves viral control in the lung.',
 '384': 'Epidemiological disease burden from noncommunicable diseases is more prevalent in low economic settings.',
 '385': 'Epigenetic modulating agents (EMAs) modulate antitumor immune response in a cancer model system.',
 '386': 'Errors in peripheral IV drug administration are most common during bolus administration and multiple-step medicine preparations.',
 '388': 'Ethanol stress decreases the expression of IBP in bacteria.',
 '399': 'Exposure to fine particulate air pollution is relate to anxiety prevalence.',
 '410': 'Febrile seizures increase the threshold for development of epilepsy.',
 '411': 'Febrile seizures reduce the threshold for development of epilepsy.',
 '415': 'Female carriers of the Apolipoprotein E4 (APOE4) allele have increased risk for dementia.',
 '421': 'Flexible molecules experience greater steric hindrance in the tumor microenviroment than rigid molecules.',
 '431': 'FoxO3a activation in neuronal death is mediated by reactive oxygen species (ROS).',
 '436': 'Free histones are degraded by a Rad53-dependent mechanism once DNA has been replicated.',
 '437': 'Functional consequences of genomic alterations due to Myelodysplastic syndrome (MDS) are poorly understood due to the lack of an animal model.',
 '439': 'Fz/PCP-dependent Pk localizes to the anterior membrane of neuroectoderm cells during zebrafish neuralation',
 '440': 'Fz/PCP-dependent Pk localizes to the anterior membrane of notochord cells during zebrafish neuralation.',
 '443': 'GATA-3 is important for hematopoietic stem cell (HSC) function.',
 '452': 'Gene expression does not vary appreciably across genetically identical cells.',
 '475': 'Glycolysis is one of the primary glycometabolic pathways in cells.',
 '478': 'Golli-deficient T-cells prefer to differentiate into an anergic phenotype in the adaptive immune response when there are increased levels of Ca2+ in the cytosol.',
 '491': 'HNF4A mutations can cause diabetes in mutant carriers by the age of 14 years',
 '501': 'Headaches are not correlated with cognitive impairment.',
 '502': 'Healthcare delivery efficiency in crowded delivery centers is impaired by improving structural, logistical, and interpersonal elements.',
 '507': 'Helminths interfere with immune system control of macrophages activated by IL-4 favor Mycobacterium tuberculosis replication.',
 '508': 'Hematopoietic Stem Cell purification reaches purity rate of up to 50%.',
 '513': 'High cardiopulmonary fitness causes increased mortality rate.',
 '514': 'High dietary calcium intakes are unnecessary for prevention of secondary hyperparathyroidism in subjects with 25(OH)D levels above 75 nmol/liter.',
 '516': 'High levels of CRP reduces the risk of exacerbations in chronic obstructive pulmonary disease (COPD).',
 '517': 'High levels of copeptin decrease risk of diabetes.',
 '521': 'High-sensitivity cardiac troponin T (HSCT-T) dosage may not be diagnostic if the onset of symptoms occurs less than 3 hours before acute myocardial injury (AMI).',
 '525': 'Histone demethylase recruitment and a transient decrease in histone methylation is necessary for ligand-dependent induction of transcription by nuclear receptors.',
 '527': 'Homozygous deletion of murine Sbds gene from osterix-expressing mesenchymal stem and progenitor cells (MPCs) prevents oxidative stress.',
 '528': 'Human T-lymphotropic virus type-I-associated myelopathy / tropical spastic paraparesis (HAM/TSP) patients produce Immunoglobulin G (IgG) antibodies which cross-react with an immunodominant epitope in Tax.',
 '532': 'Hyperfibrinogenemia decreases rates of femoropopliteal bypass thrombosis.',
 '533': 'Hyperfibrinogenemia increases rates of femoropopliteal bypass thrombosis.',
 '535': 'Hypertension is frequently observed in type 1 diabetes patients.',
 '536': 'Hypocretin neurones induce panicprone state in rats.',
 '539': 'Hypoglycemia increases the risk of dementia.',
 '540': 'Hypothalamic glutamate neurotransmission is crucial to energy balance.',
 '544': 'IFIT1 restricts viral replication by sequestrating mis-capped viral RNAs.',
 '549': 'IRG1 has antiviral effects against neurotropic viruses.',
 '551': 'ITAM phosphorylation prevents the transfer of the T cell receptor (TCR) signal from the echo-domain to the cytoplasmic tail of the T cell receptor (TCR).',
 '552': 'IgA plasma cells that are specific for transglutaminase 2 accumulate in the duodenal mucosa on commencement of a gluten-free diet.',
 '554': 'Immune complex triggered cell death leads to extracellular release of neutrophil protein HMGB1.',
 '560': 'Immune responses result in the development of inflammatory Th17 cells and anti-inflammatory iTregs.',
 '569': 'In adult tissue, most T cells are memory T cells.',
 '575': 'In domesticated populations of Saccharomyces cerevisiae, whole chromosome aneuploidy is very uncommon.',
 '577': 'In mice, P. chabaudi parasites are able to proliferate faster early in infection when inoculated at lower numbers than when inoculated at high numbers.',
 '578': 'In mouse models, the loss of CSF1R facilitates MOZ-TIF2-induced leuekmogenesis.',
 '587': 'In transgenic mice harboring green florescent protein under the control of the Sox2 promoter, less than ten percent of the cells with green florescent colocalize with cell proliferation markers.',
 '589': 'In young and middle-aged adults, current or remote uses of ADHD medications do not increase the risk of serious cardiovascular events.',
 '593': 'Incidence of heart failure decreased by 10% in women since 1979.',
 '597': 'Incidence rates of cervical cancer have decreased.',
 '598': 'Incidence rates of cervical cancer have increased due to nationwide screening programs based primarily on cytology to detect uterine cervical cancer.',
 '613': 'Increased microtubule acetylation repairs LRRK2 Roc-COR domain mutation induced locomotor deficits.',
 '619': 'Increased vessel density along with a reduction in fibrosis decreases the efficacy of chemotherapy treatments.',
 '623': 'Individuals with low serum vitamin D concentrations have increased risk of multiple sclerosis.',
 '628': 'Infection of human T-cell lymphotropic virus type 1 is most frequent in individuals of African origin.',
 '636': 'Inositol lipid 3-phosphatase PTEN converts Ptdlns(3,4)P 2 into phosphatidylinositol 4-phosphate.',
 '637': 'Input from  mental and physical health care professionals is effective at decreasing homelessness.',
 '641': 'Insomnia can be effectively treated with cognitive behavioral therapy.',
 '644': 'Insulin increases risk of severe kidney failure.',
 '649': 'Integrating classroom-based collaborative learning with Web-based collaborative learning leads to subpar class performance',
 '659': 'Ivermectin is used to treat lymphatic filariasis.',
 '660': 'Ivermectin is used to treat onchocerciasis.',
 '674': 'LDL cholesterol has no involvement in the development of cardiovascular disease.',
 '684': 'Lack of clpC does not affect sporulation efficiency in Bacillus subtilis cells.',
 '690': 'Less than 10% of the gabonese children with Schimmelpenning-Feuerstein-Mims syndrome (SFM) had a plasma lactate of more than 5mmol/L.',
 '691': 'Leukemia associated Rho guanine nucleotide-exchange factor represses RhoA in response to SRC activation.',
 '692': 'Leuko-increased blood increases infectious complications in red blood cell transfusion.',
 '693': 'Leuko-reduced blood reduces infectious complications in red blood cell transfusion.',
 '700': 'Localization of PIN1 in the Arabidopsis embryo does not require VPS9a',
 '702': 'Localization of PIN1 in the roots of Arabidopsis does not require VPS9a',
 '715': 'Low expression of miR7a does represses target genes and exerts a biological function in ovaries.',
 '716': 'Low expression of miR7a exerts a biological function in testis.',
 '718': 'Low nucleosome occupancy correlates with low methylation levels across species.',
 '721': 'Lupus-prone mice infected with curliproducing bacteria have higher autoantibody titers compared to controls.',
 '723': 'Ly49Q directs the organization of neutrophil migration to inflammation sites by regulating membrane raft functions.',
 '727': 'Ly6C hi monocytes have a lower inflammatory capacity compared to their Ly6C lo counterparts.',
 '728': 'Ly6C hi monocytes have a lower inflammatory capacity than Ly6C lo monocytes.',
 '729': 'Lymphadenopathy is observed in knockin mouse lacking the SHP-2 MAPK pathway.',
 '742': 'Macrolides have no protective effect against myocardial infarction.',
 '743': 'Macrolides protect against myocardial infarction.',
 '744': "Macropinocytosis contributes to a cell's supply of amino acids via the intracellular uptake of protein.",
 '756': 'Many proteins in human cells can be post-translationally modified at lysine residues via acetylation.',
 '759': 'Mathematical models predict that using Artemisinin-based combination therapy over nongametocytocidal drugs have a dramatic impact in reducing malaria transmission.',
 '768': 'Mercaptopurine is anabolized into the inactive methylmercaptopurine by thiopurine methyltrasnferase (TPMT).',
 '770': 'Metastatic colorectal cancer treated with a single agent fluoropyrimidines resulted in reduced efficacy and lower quality of life when compared with oxaliplatin-based chemotherapy in elderly patients.',
 '775': 'Mice defective for deoxyribonucleic acid (DNA) polymerase I (polI) reveal increased sensitivity to ionizing radiation (IR).',
 '781': 'Mice that lack Interferon-γ or its receptor exhibit high resistance to experimental autoimmune myocarditis.',
 '783': 'Mice without IFN-γ or its receptor are resistant to EAM induced with α-MyHC/CFA.',
 '784': 'MicroRNA is involved in the regulation of Neural Stem Cell (NSC) differentiation and proliferation dynamic homeostasis',
 '785': 'Microarray results from culture-amplified mixtures of serotypes correlate poorly with microarray results from uncultured mixtures.',
 '793': 'Mitochondria are uninvolved in apoptosis.',
 '800': 'Modifying the epigenome in the brain affects the normal human aging process by affecting certain genes related to neurogenesis.',
 '805': 'Monoclonal antibody targeting of N-cadherin inhibits metastasis.',
 '808': 'Most termination events in Okazaki fragments are sequence specific.',
 '811': 'Mutant mice lacking SVCT2 have greatly increased ascorbic acid levels in both brain and adrenals.',
 '814': 'Mutations in G-Beta protein GNB2 are present in many cancers, resulting in loss of interaction with G-alpha subunits and concomitant activation of AKT pathway.',
 '820': 'N-terminal cleavage increases success identifying transcription start sites.',
 '821': 'N-terminal cleavage reduces success identifying transcription start sites.',
 '823': 'N348I mutations cause resistance to zidovudine (AZT).',
 '830': 'NF2 (Merlin) causes phosphorylation and subsequent cytoplasmic sequestration of YAP in Drosophila by activating LATS1/2 kinases.',
 '831': 'NF2 (Merlin) prevents phosphorylation and subsequent cytoplasmic sequestration of YAP in Drosophila.',
 '832': 'NFAT4 activation requires IP3R-mediated Ca2+ mobilization.',
 '834': 'NOX2-independent pathways can generate peroxynitrite by reacting with nitrogen intermediates.',
 '837': 'NR5A2 is important in development of endometrial tissues.',
 '839': 'Nanoparticles can be targeted against specific cell types by incorporating aptamers into lipid nanoparticles.',
 '845': 'Neutrophil extracellular traps (NETs) are released by ANCA-stimulated neutrophils.',
 '847': 'New drugs for tuberculosis often do not penetrate the necrotic portion of a tuberculosis lesion in high concentrations.',
 '852': 'Non-invasive ventilation use should be decreased if there is inadequate response to conventional treatment.',
 '859': 'Normal expression of RUNX1 has tumor-promoting effects.',
 '870': 'Obesity decreases life quality.',
 '873': 'Obesity is determined solely by environmental factors.',
 '879': 'Occupancy of ribosomes by IncRNAs do not make functional peptides.',
 '880': 'Occupancy of ribosomes by IncRNAs mirror 5 0-UTRs',
 '882': 'Omnivores produce less trimethylamine N-oxide from dietary I-carnitine than vegetarians.',
 '887': 'Only a minority of cells survive development after differentiation into stress-resistant spores.',

In [16]:
qrels

{'1': {'31715818': 1},
 '3': {'14717500': 1},
 '5': {'13734012': 1},
 '13': {'1606628': 1},
 '36': {'5152028': 1, '11705328': 1},
 '42': {'18174210': 1},
 '48': {'13734012': 1},
 '49': {'5953485': 1},
 '50': {'12580014': 1},
 '51': {'45638119': 1},
 '53': {'45638119': 1},
 '54': {'49556906': 1},
 '56': {'4709641': 1},
 '57': {'4709641': 1},
 '70': {'5956380': 1, '4414547': 1},
 '72': {'6076903': 1},
 '75': {'4387784': 1},
 '94': {'1215116': 1},
 '99': {'18810195': 1},
 '100': {'4381486': 1},
 '113': {'6157837': 1},
 '115': {'33872649': 1},
 '118': {'6372244': 1},
 '124': {'4883040': 1},
 '127': {'21598000': 1},
 '128': {'8290953': 1},
 '129': {'27768226': 1},
 '130': {'27768226': 1},
 '132': {'7975937': 1},
 '133': {'38485364': 1,
  '6969753': 1,
  '17934082': 1,
  '16280642': 1,
  '12640810': 1},
 '137': {'26016929': 1},
 '141': {'6955746': 1, '14437255': 1},
 '142': {'10582939': 1},
 '143': {'10582939': 1},
 '146': {'10582939': 1},
 '148': {'1084345': 1},
 '163': {'18872233': 1},
 '171': {'12670680': 1},
 '179': {'16322674': 1, '27123743': 1, '23557241': 1, '17450673': 1},
 '180': {'16966326': 1},
 '183': {'12827098': 1},
 '185': {'18340282': 1},
 '198': {'2177022': 1},
 '208': {'13519661': 1},
 '212': {'22038539': 1},
 '213': {'13625993': 1},
 '216': {'21366394': 1},
 '217': {'21366394': 1},
 '218': {'21366394': 1},
 '219': {'21366394': 1},
 '230': {'3067015': 1},
 '232': {'10536636': 1},
 '233': {'4388470': 1},
 '236': {'4388470': 1},
 '237': {'4942718': 1},
 '238': {'2251426': 1},
 '239': {'14079881': 1},
 '248': {'1568684': 1},
 '249': {'1568684': 1},
 '261': {'1122279': 1, '10697096': 1},
 '268': {'970012': 1},
 '269': {'970012': 1},
 '274': {'11614737': 1},
 '275': {'4961038': 1, '14241418': 1, '14819804': 1},
 '279': {'14376683': 1},
 '294': {'10874408': 1},
 '295': {'20310709': 1},
 '298': {'39381118': 1},
 '300': {'3553087': 1},
 '303': {'4388470': 1},
 '312': {'6173523': 1},
 '314': {'4347374': 1},
 '324': {'2014909': 1},
 '327': {'17997584': 1},
 '338': {'23349986': 1},
 '343': {'7873737': 1, '5884524': 1},
 '350': {'16927286': 1},
 '354': {'8774475': 1},
 '362': {'38587347': 1},
 '380': {'19005293': 1},
 '384': {'13770184': 1},
 '385': {'9955779': 1, '9767444': 1},
 '386': {'16495649': 1},
 '388': {'1148122': 1},
 '399': {'791050': 1},
 '410': {'14924526': 1},
 '411': {'14924526': 1},
 '415': {'6309659': 1},
 '421': {'11172205': 1},
 '431': {'28937856': 1},
 '436': {'14637235': 1},
 '437': {'18399038': 1},
 '439': {'4423559': 1},
 '440': {'4423559': 1},
 '443': {'10165258': 1},
 '452': {'12804937': 1, '464511': 1},
 '475': {'18678095': 1},
 '478': {'14767844': 1},
 '491': {'56893404': 1},
 '501': {'17930286': 1},
 '502': {'13071728': 1},
 '507': {'30774694': 1},
 '508': {'13980338': 1},
 '513': {'13230773': 1},
 '514': {'16256507': 1},
 '516': {'29564505': 1},
 '517': {'15663829': 1},
 '521': {'34873974': 1},
 '525': {'13639330': 1},
 '527': {'3863543': 1},
 '528': {'5476778': 1},
 '532': {'12991445': 1},
 '533': {'12991445': 1},
 '535': {'39368721': 1},
 '536': {'16056514': 1},
 '539': {'13282296': 1},
 '540': {'11886686': 1, '25007443': 1},
 '544': {'24221369': 1},
 '549': {'9433958': 1},
 '551': {'33499189': 1},
 '552': {'1471041': 1},
 '554': {'1049501': 1},
 '560': {'40096222': 1},
 '569': {'23460562': 1},
 '575': {'10300888': 1},
 '577': {'5289038': 1},
 '578': {'8764879': 1},
 '587': {'16999023': 1},
 '589': {'10984005': 1},
 '593': {'19675911': 1},
 '597': {'12779444': 1, '36355784': 1, '25742130': 1},
 '598': {'25742130': 1},
 '613': {'9638032': 1},
 '619': {'20888849': 1, '2565138': 1},
 '623': {'17000834': 1},
 '628': {'24512064': 1},
 '636': {'24294572': 1},
 '637': {'25649714': 1},
 '641': {'5912283': 1, '31554917': 1},
 '644': {'13619127': 1},
 '649': {'12789595': 1},
 '659': {'1215116': 1},
 '660': {'1215116': 1},
 '674': {'2095573': 1},
 '684': {'4942718': 1},
 '690': {'18750453': 1},
 '691': {'10991183': 1},
 '692': {'24088502': 1},
 '693': {'24088502': 1},
 '700': {'4350400': 1},
 '702': {'4350400': 1},
 '715': {'18421962': 1},
 '716': {'18421962': 1},
 '718': {'17587795': 1},
 '721': {'1834762': 1},
 '723': {'5531479': 1},
 '727': {'7521113': 1},
 '728': {'7521113': 1, '36444198': 1},
 '729': {'26851674': 1},
 '742': {'32159283': 1},
 '743': {'32159283': 1},
 '744': {'8460275': 1},
 '756': {'2831620': 1},
 '759': {'1805641': 1},
 '768': {'6421792': 1},
 '770': {'15476777': 1},
 '775': {'32275758': 1},
 '781': {'24338780': 1},
 '783': {'40632104': 1},
 '784': {'2356950': 1},
 '785': {'12471115': 1},
 '793': {'8551160': 1},
 '800': {'22543403': 1},
 '805': {'22180793': 1},
 '808': {'36606083': 1},
 '811': {'19799455': 1},
 '814': {'33387953': 1},
 '820': {'8646760': 1},
 '821': {'8646760': 1},
 '823': {'15319019': 1},
 '830': {'1897324': 1},
 '831': {'1897324': 1},
 '832': {'30303335': 1},
 '834': {'5483793': 1},
 '837': {'15928989': 1},
 '839': {'1469751': 1},
 '845': {'17741440': 1},
 '847': {'16787954': 1},
 '852': {'13843341': 1},
 '859': {'1982286': 1},
 '870': {'195689316': 1},
 '873': {'1180972': 1,
  '19307912': 1,
  '27393799': 1,
  '29025270': 1,
  '3315558': 1},
 '879': {'8426046': 1},
 '880': {'8426046': 1},
 '882': {'14803797': 1},
 '887': {'18855191': 1},
 '903': {'10648422': 1},
 '904': {'7370282': 1},
 '907': {'6923961': 1},
 '911': {'11254556': 1},
 '913': {'3203590': 1},
 '914': {'3203590': 1},
 '921': {'1642727': 1},
 '922': {'17077004': 1},
 '936': {'5483793': 1},
 '956': {'12956194': 1},
 '957': {'123859': 1},
 '960': {'8780599': 1},
 '967': {'2119889': 1, '8997410': 1},
 '971': {'46695481': 1, '27873158': 1, '28617573': 1, '9764256': 1},
 '975': {'5304891': 1},
 '982': {'2988714': 1},
 '985': {'6828370': 1},
 '993': {'16472469': 1},
 '1012': {'9745001': 1},
 '1014': {'6277638': 1},
 '1019': {'11603066': 1},
 '1020': {'9433958': 1},
 '1021': {'9433958': 1},
 '1024': {'5373138': 1},
 '1029': {'13923140': 1, '13940200': 1, '11899391': 1},
 '1041': {'25254425': 1, '16626264': 1},
 '1049': {'12486491': 1},
 '1062': {'20381484': 1},
 '1086': {'39281140': 1},
 '1088': {'37549932': 1},
 '1089': {'17628888': 1},
 '1099': {'7662206': 1},
 '1100': {'7662206': 1},
 '1104': {'3898784': 1},
 '1107': {'20532591': 1},
 '1110': {'13770184': 1},
 '1121': {'4456756': 1},
 '1130': {'17997584': 1},
 '1132': {'33499189': 1, '9283422': 1},
 '1137': {'33370': 1},
 '1140': {'12009265': 1},
 '1144': {'10071552': 1},
 '1146': {'13906581': 1},
 '1150': {'11369420': 1},
 '1163': {'15305881': 1},
 '1175': {'31272411': 1},
 '1179': {'31272411': 1},
 '1180': {'31272411': 1},
 '1185': {'16737210': 1},
 '1187': {'52873726': 1},
 '1191': {'30655442': 1},
 '1194': {'11419230': 1},
 '1196': {'25649714': 1},
 '1197': {'25649714': 1},
 '1199': {'16760369': 1},
 '1200': {'3441524': 1},
 '1202': {'3475317': 1},
 '1204': {'31141365': 1},
 '1207': {'18909530': 1},
 '1213': {'14407673': 1},
 '1216': {'24142891': 1},
 '1221': {'19736671': 1},
 '1225': {'9650982': 1},
 '1226': {'13777138': 1},
 '1232': {'13905670': 1},
 '1241': {'4427392': 1},
 '1245': {'7662395': 1},
 '1259': {'24341590': 1},
 '1262': {'44172171': 1},
 '1266': {'37480103': 1},
 '1270': {'13900610': 1},
 '1271': {'13768432': 1},
 '1272': {'17081238': 1},
 '1273': {'11041152': 1},
 '1274': {'12428814': 1, '27731651': 1, '4406819': 1},
 '1278': {'11335781': 1},
 '1279': {'11335781': 1},
 '1280': {'4387784': 1},
 '1281': {'4387784': 1},
 '1282': {'23649163': 1},
 '1290': {'4687948': 1},
 '1292': {'56893404': 1},
 '1298': {'11718220': 1},
 '1303': {'12631697': 1},
 '1316': {'27910499': 1},
 '1319': {'16284655': 1},
 '1320': {'16284655': 1},
 '1332': {'5304891': 1},
 '1335': {'27910499': 1},
 '1336': {'27910499': 1},
 '1337': {'20231138': 1},
 '1339': {'15482274': 1},
 '1344': {'9559146': 1},
 '1352': {'12885341': 1},
 '1359': {'11614737': 1},
 '1362': {'8290953': 1},
 '1363': {'8290953': 1},
 '1368': {'2425364': 1},
 '1370': {'2425364': 1},
 '1379': {'16322674': 1, '27123743': 1, '23557241': 1, '17450673': 1},
 '1382': {'17755060': 1},
 '1385': {'306006': 1},
 '1389': {'23895668': 1},
 '1395': {'17717391': 1}}

In [17]:
queries_df = (pd.DataFrame.from_dict(queries, orient="index")
              .reset_index()
              .rename(columns={'index': 'query_id', 0: 'query_text'}))

queries_df

    query_id                                         query_text
0          1  0-dimensional biomaterials show inductive prop...
1          3  1,000 genomes project enables mapping of genet...
2          5         1/2000 in UK have abnormal PrP positivity.
3         13  5% of perinatal mortality is due to low birth ...
4         36  A deficiency of vitamin B12 increases blood le...
..       ...                                                ...
295     1379  Women with a higher birth weight are more like...
296     1382  aPKCz causes tumour enhancement by affecting g...
297     1385   cSMAC formation enhances weak ligand signalling.
298     1389  mTORC2 regulates intracellular cysteine levels...
299     1395  p16INK4A accumulation is  linked to an abnorma...

[300 rows x 2 columns]

In [18]:
qrels_list = []
for query_id, docs in qrels.items():
    for doc_id, relevance in docs.items():
        qrels_list.append({
            'query_id': query_id,
            'doc_id': doc_id,
            'relevance': relevance
        })

qrels_df = pd.DataFrame(qrels_list)
qrels_df.head(10)

  query_id    doc_id  relevance
0        1  31715818          1
1        3  14717500          1
2        5  13734012          1
3       13   1606628          1
4       36   5152028          1
5       36  11705328          1
6       42  18174210          1
7       48  13734012          1
8       49   5953485          1
9       50  12580014          1

In [19]:
qrels_df['relevance'].value_counts()

relevance
1    339
Name: count, dtype: int64

# Test with querie number 1

In [20]:
queries_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   query_id    300 non-null    str
 1   query_text  300 non-null    str
dtypes: str(2)
memory usage: 32.2 KB

In [21]:
query = queries_df.loc[queries_df['query_id'] == '70', 'query_text'].iloc[0]

In [23]:
query_embedding = embedding_model.encode(
    [query],
    normalize_embeddings=True
)

In [24]:
scores, indices = index.search(
    query_embedding,
    k=10
)

In [25]:
for rank, idx in enumerate(indices[0], start=1):

    print(f"\nRank {rank}")
    print("Score:", scores[0][rank - 1])
    print("ID:", corpus_df.iloc[idx]["index"])

Rank 1
Score: 0.78618187
ID: 4414547

Rank 2
Score: 0.7666184
ID: 11903247

Rank 3
Score: 0.76654863
ID: 5956380

Rank 4
Score: 0.7640258
ID: 31624828

Rank 5
Score: 0.75287116
ID: 7225911

Rank 6
Score: 0.750954
ID: 21557055

Rank 7
Score: 0.747499
ID: 9483851

Rank 8
Score: 0.73814404
ID: 12240507

Rank 9
Score: 0.7373251
ID: 2582169

Rank 10
Score: 0.736439
ID: 36464673

In [26]:
qrels_df.loc[qrels_df['query_id'] == '70', 'doc_id']

15    5956380
16    4414547
Name: doc_id, dtype: str

# Evaluation Using Ranx

### Create Run Dict

In [28]:
run_dict = {}

for i, row in queries_df.iterrows():
    query_id = row['query_id']  
    query_txt = row['query_text']
    
    # Get embeddings and search
    query_embedding = embedding_model.encode(
        [query_txt],
        normalize_embeddings=True
    )
    scores, indices = index.search(query_embedding, k=10)
    
    doc_scores = {}
    for rank, idx in enumerate(indices[0], start=1): 
        doc_id = corpus_df.iloc[idx]["index"]
        score = scores[0][rank - 1]
        doc_scores[doc_id] = float(score)  
    
    run_dict[query_id] = doc_scores

In [29]:
run_dict

{'1': {'4346436': 0.7425371408462524,
  '17388232': 0.7204512357711792,
  '16962732': 0.7052040696144104,
  '29638116': 0.7000970244407654,
  '927561': 0.6981079578399658,
  '21456232': 0.694959282875061,
  '23763738': 0.6948124766349792,
  '2121272': 0.691043496131897,
  '14103509': 0.6909676790237427,
  '16736872': 0.6894996762275696},
 '3': {'4414547': 0.7115472555160522,
  '10944947': 0.709050714969635,
  '19058822': 0.6994143128395081,
  '23389795': 0.696605920791626,
  '14717500': 0.6939852237701416,
  '2739854': 0.6827147006988525,
  '4632921': 0.6799712181091309,
  '10145528': 0.6767180562019348,
  '3823862': 0.6738227605819702,
  '13791788': 0.6707893013954163},
 '5': {'13734012': 0.7466669082641602,
  '27063470': 0.728550374507904,
  '25261168': 0.6832140684127808,
  '18617259': 0.6673370003700256,
  '23124332': 0.6667923927307129,
  '11349166': 0.6647814512252808,
  '21550246': 0.6647285223007202,
  '1583041': 0.6593499183654785,
  '841371': 0.6496787071228027,
  '19945096': 0.6411488056182861},
 '13': {'7662395': 0.7227811813354492,
  '4791384': 0.7146446108818054,
  '1263446': 0.7108239531517029,
  '16204011': 0.7099629640579224,
  '33257464': 0.7012101411819458,
  '1606628': 0.6962383389472961,
  '8529693': 0.6942601799964905,
  '13791044': 0.692036509513855,
  '28633594': 0.6874050498008728,
  '30786800': 0.6871127486228943},
 '36': {'18557974': 0.7585160732269287,
  '37424881': 0.7392795085906982,
  '21636085': 0.7354607582092285,
  '11705328': 0.7350071668624878,
  '3215494': 0.7305281162261963,
  '33409100': 0.7269995808601379,
  '10557471': 0.7259092330932617,
  '13801259': 0.7229294776916504,
  '18256197': 0.7208735942840576,
  '16252863': 0.7076901793479919},
 '42': {'18174210': 0.8372566103935242,
  '27889071': 0.8024379014968872,
  '40913091': 0.7766600847244263,
  '32481310': 0.7332508563995361,
  '24042919': 0.7254448533058167,
  '45218443': 0.7246074676513672,
  '1145473': 0.7214227914810181,
  '6315132': 0.710060179233551,
  '13959707': 0.7047979831695557,
  '8083310': 0.694847583770752},
 '48': {'27063470': 0.7429801225662231,
  '11349166': 0.7341349124908447,
  '23203102': 0.6830880641937256,
  '13734012': 0.6824072599411011,
  '29955650': 0.673255443572998,
  '18617259': 0.6631237268447876,
  '5850219': 0.6605445146560669,
  '3413083': 0.6514443159103394,
  '22194407': 0.6455775499343872,
  '25261168': 0.6368613243103027},
 '49': {'5953485': 0.859001874923706,
  '5702790': 0.7774028182029724,
  '7029990': 0.7605112195014954,
  '23913146': 0.7585821151733398,
  '8006440': 0.7346342206001282,
  '22362025': 0.7295984625816345,
  '5409325': 0.7271777391433716,
  '12652963': 0.726763904094696,
  '1333643': 0.7145686149597168,
  '86602746': 0.7139208912849426},
 '50': {'12580014': 0.7778752446174622,
  '25738896': 0.7338417172431946,
  '18488986': 0.7245696783065796,
  '19736671': 0.7021279335021973,
  '13989491': 0.6983600854873657,
  '36950726': 0.695376992225647,
  '29785642': 0.6939515471458435,
  '19343151': 0.6919485330581665,
  '39559521': 0.6828911304473877,
  '15405204': 0.680855393409729},
 '51': {'45638119': 0.8598312139511108,
  '24349992': 0.7328059673309326,
  '1866911': 0.7251258492469788,
  '36212758': 0.7083908319473267,
  '14663842': 0.7025744915008545,
  '43385013': 0.702164888381958,
  '17648235': 0.7014912366867065,
  '3067015': 0.7011576890945435,
  '4886637': 0.7007107138633728,
  '31311495': 0.7005286812782288},
 '53': {'45638119': 0.8587986826896667,
  '24349992': 0.7261654734611511,
  '1866911': 0.7247664928436279,
  '15113221': 0.7205417156219482,
  '4418878': 0.7176662683486938,
  '6517763': 0.7171635031700134,
  '12762485': 0.711907148361206,
  '36212758': 0.7112442255020142,
  '7228140': 0.7093142867088318,
  '43385013': 0.7083582878112793},
 '54': {'49556906': 0.862829327583313,
  '3973445': 0.7938494086265564,
  '3419709': 0.7733349800109863,
  '24721866': 0.7717630863189697,
  '32408470': 0.75890052318573,
  '26025820': 0.7557376027107239,
  '1907601': 0.7538050413131714,
  '7005276': 0.7527135610580444,
  '22621251': 0.7492027878761292,
  '1590744': 0.7468860149383545},
 '56': {'4709641': 0.8639906644821167,
  '4459491': 0.77162104845047,
  '13814480': 0.7708137035369873,
  '10795063': 0.7541048526763916,
  '31347396': 0.739947497844696,
  '13293033': 0.7390632033348083,
  '11659421': 0.7293771505355835,
  '30351165': 0.7257653474807739,
  '24725136': 0.7246222496032715,
  '36637129': 0.7231976985931396},
 '57': {'4709641': 0.8632774353027344,
  '4459491': 0.7680786848068237,
  '13814480': 0.767816424369812,
  '10795063': 0.7548179626464844,
  '13293033': 0.7325913906097412,
  '36637129': 0.7306616306304932,
  '31347396': 0.7295613884925842,
  '30351165': 0.7291849851608276,
  '11659421': 0.725740909576416,
  '1964163': 0.7189618945121765},
 '70': {'4414547': 0.7861818671226501,
  '11903247': 0.7666183710098267,
  '5956380': 0.7665486335754395,
  '31624828': 0.7640258073806763,
  '7225911': 0.7528711557388306,
  '21557055': 0.7509539723396301,
  '9483851': 0.7474989891052246,
  '12240507': 0.738144040107727,
  '2582169': 0.7373250722885132,
  '36464673': 0.7364389896392822},
 '72': {'24335068': 0.7025611400604248,
  '14296612': 0.7010115385055542,
  '2119889': 0.6991431713104248,
  '6076903': 0.6985542178153992,
  '8997410': 0.697196364402771,
  '18576103': 0.6970547437667847,
  '40383969': 0.6915538311004639,
  '36399109': 0.6908411383628845,
  '9021186': 0.6898181438446045,
  '18895793': 0.6882242560386658},
 '75': {'4387784': 0.8099989295005798,
  '25657127': 0.754784345626831,
  '37768883': 0.7483001947402954,
  '29214508': 0.7407554388046265,
  '36233757': 0.7390271425247192,
  '38805486': 0.7363798022270203,
  '13965483': 0.7053112387657166,
  '26488879': 0.7006362676620483,
  '1744752': 0.6935349106788635,
  '12691537': 0.6857112646102905},
 '94': {'12409683': 0.6632221937179565,
  '18025240': 0.6631841063499451,
  '1215116': 0.6530834436416626,
  '10617916': 0.6431294679641724,
  '1805641': 0.6329755187034607,
  '3929361': 0.6272197961807251,
  '13966946': 0.624446451663971,
  '18074797': 0.6209309101104736,
  '9110810': 0.6147638559341431,
  '15237660': 0.6139978170394897},
 '99': {'18810195': 0.7052620649337769,
  '13578199': 0.6831480264663696,
  '15795880': 0.6813740730285645,
  '36233757': 0.6810176968574524,
  '4387784': 0.6780239343643188,
  '14180217': 0.6769059896469116,
  '12265561': 0.676012396812439,
  '2617858': 0.67496657371521,
  '44947611': 0.6704246997833252,
  '4396105': 0.6689650416374207},
 '100': {'4381486': 0.7804166078567505,
  '14550841': 0.7739593982696533,
  '13980338': 0.7407062649726868,
  '9154703': 0.7406901121139526,
  '11020675': 0.7327747344970703,
  '30152134': 0.7298411130905151,
  '3321943': 0.7282994389533997,
  '1381673': 0.7270749807357788,
  '18374364': 0.7257419228553772,
  '4421787': 0.7246251702308655},
 '113': {'25816994': 0.7978875637054443,
  '6157837': 0.7861096858978271,
  '44030361': 0.7572194337844849,
  '1759213': 0.7491170763969421,
  '3825750': 0.747104287147522,
  '40790033': 0.7459768056869507,
  '4678846': 0.7391132116317749,
  '26199970': 0.7247235774993896,
  '10072941': 0.7197065949440002,
  '140098548': 0.719241738319397},
 '115': {'33872649': 0.685386598110199,
  '15879544': 0.594293475151062,
  '4321295': 0.5724864602088928,
  '18855191': 0.5639392137527466,
  '695938': 0.5562808513641357,
  '96222213': 0.5549682378768921,
  '4942718': 0.5543954372406006,
  '12824568': 0.5502744317054749,
  '1234098': 0.5484951734542847,
  '15414628': 0.5476405620574951},
 '118': {'4465735': 0.8685069680213928,
  '6372244': 0.8682951927185059,
  '32454714': 0.7383981943130493,
  '52805891': 0.7274723052978516,
  '15578265': 0.7227245569229126,
  '4492358': 0.719401478767395,
  '15274349': 0.7127336263656616,
  '21956124': 0.7078739404678345,
  '34603465': 0.7068914771080017,
  '20148808': 0.7056095600128174},
 '124': {'4883040': 0.8541406393051147,
  '7111021': 0.8046287298202515,
  '21479231': 0.7517558336257935,
  '31363207': 0.7515147924423218,
  '13899137': 0.7432398200035095,
  '22414304': 0.7291390895843506,
  '14319754': 0.7267701625823975,
  '13914633': 0.7223501205444336,
  '1986482': 0.719260573387146,
  '13901073': 0.7181218862533569},
 '127': {'35231675': 0.7085556387901306,
  '21598000': 0.6999532580375671,
  '38623601': 0.6966404914855957,
  '20054396': 0.6804295182228088,
  '23618826': 0.6796793341636658,
  '86231298': 0.6778144836425781,
  '39863735': 0.6771789789199829,
  '14178995': 0.6760885119438171,
  '26495128': 0.6752334833145142,
  '12685434': 0.6751963496208191},
 '128': {'12549585': 0.6854691505432129,
  '79447': 0.666649580001831,
  '12513972': 0.6611908674240112,
  '5254741': 0.6606267094612122,
  '2260571': 0.6602651476860046,
  '25300664': 0.6588855981826782,
  '19854543': 0.6556229591369629,
  '33569870': 0.6523886919021606,
  '23785605': 0.6512444019317627,
  '17168045': 0.6491734981536865},
 '129': {'27768226': 0.7455552816390991,
  '6477536': 0.663608193397522,
  '16979690': 0.6320993900299072,
  '39652608': 0.6265307664871216,
  '4688277': 0.6131314039230347,
  '6319826': 0.5997451543807983,
  '790598': 0.5973049402236938,
  '7547329': 0.5913736820220947,
  '22711954': 0.5888426303863525,
  '14319754': 0.5752029418945312},
 '130': {'27768226': 0.7843081951141357,
  '6477536': 0.6412789821624756,
  '16979690': 0.6400315761566162,
  '39652608': 0.6299352645874023,
  '4688277': 0.6262134313583374,
  '22711954': 0.60951167345047,
  '6319826': 0.6060894727706909,
  '790598': 0.6054157614707947,
  '7547329': 0.5948249101638794,
  '26532518': 0.5903384685516357},
 '132': {'15648443': 0.7235338687896729,
  '3866315': 0.7180095911026001,
  '39903312': 0.7179134488105774,
  '2443495': 0.716805100440979,
  '9159125': 0.7139676809310913,
  '6407356': 0.7130596041679382,
  '43334921': 0.7112917900085449,
  '20732789': 0.7067621946334839,
  '24730100': 0.7065295577049255,
  '6945691': 0.7059109210968018},
 '133': {'16280642': 0.827407956123352,
  '86694016': 0.7924894094467163,
  '35660758': 0.7836673259735107,
  '12640810': 0.7801911234855652,
  '17934082': 0.7672538757324219,
  '17194716': 0.7582635879516602,
  '36345185': 0.7557798624038696,
  '9507605': 0.7488507032394409,
  '17017465': 0.7457565069198608,
  '6969753': 0.7457396984100342},
 '137': {'26016929': 0.8544807434082031,
  '24735908': 0.7087916135787964,
  '21914176': 0.6870176792144775,
  '457630': 0.6834622621536255,
  '8298120': 0.6758629083633423,
  '31208367': 0.6731710433959961,
  '26668245': 0.6646749377250671,
  '20008796': 0.6617853045463562,
  '21274919': 0.6519377827644348,
  '15968271': 0.6488766670227051},
 '141': {'14437255': 0.7779673933982849,
  '6955746': 0.7705798745155334,
  '10624000': 0.7423865795135498,
  '313394': 0.7315602898597717,
  '38794814': 0.7298194169998169,
  '18379855': 0.7170583009719849,
  '14535322': 0.6957036256790161,
  '23331269': 0.6938261985778809,
  '42330403': 0.6891285181045532,
  '1710116': 0.6886395215988159},
 '142': {'10582939': 0.7649731636047363,
  '40164383': 0.7144783735275269,
  '24101431': 0.7038198113441467,
  '43587663': 0.7002948522567749,
  '5597586': 0.6937461495399475,
  '51728753': 0.6916056871414185,
  '7224723': 0.685701847076416,
  '4416964': 0.685674786567688,
  '301866': 0.6850619316101074,
  '21884059': 0.6825620532035828},
 '143': {'10582939': 0.7854896783828735,
  '40164383': 0.7339682579040527,
  '24101431': 0.7148630619049072,
  '51728753': 0.6971112489700317,
  '5597586': 0.695762038230896,
  '4416964': 0.6929918527603149,
  '21884059': 0.6862273216247559,
  '43587663': 0.6845682859420776,
  '301866': 0.6828660368919373,
  '42601237': 0.6811925172805786},
 '146': {'10582939': 0.8135799169540405,
  '40164383': 0.7486625909805298,
  '24101431': 0.7265864610671997,
  '51728753': 0.7040280699729919,
  '24825841': 0.700023889541626,
  '4416964': 0.6988734602928162,
  '5597586': 0.6984236836433411,
  '42601237': 0.6933938264846802,
  '6280907': 0.6891798973083496,
  '24795767': 0.6831542253494263},
 '148': {'1084345': 0.8051118850708008,
  '52887689': 0.7666550278663635,
  '13072113': 0.7343357801437378,
  '10012166': 0.731730580329895,
  '56528795': 0.7294472455978394,
  '7834603': 0.7257096767425537,
  '4452659': 0.7210729718208313,
  '24347647': 0.7208110094070435,
  '3202143': 0.7198206782341003,
  '15728433': 0.7187371253967285},
 '163': {'18872233': 0.8352004885673523,
  '43220289': 0.8075884580612183,
  '19071857': 0.7954810857772827,
  '29022271': 0.7629883885383606,
  '7627167': 0.7518801689147949,
  '5824985': 0.7470788955688477,
  '40949706': 0.7398155927658081,
  '20130904': 0.712209939956665,
  '36033696': 0.6991892457008362,
  '7098463': 0.6910198926925659},
 '171': {'12670680': 0.8282521963119507,
  '28149602': 0.7487809658050537,
  '28015516': 0.7146109342575073,
  '14853989': 0.6962584853172302,
  '1834762': 0.6955957412719727,
  '14938990': 0.6837972402572632,
  '1049501': 0.683350682258606,
  '17741440': 0.6775124669075012,
  '5448119': 0.6759070158004761,
  '8137081': 0.6647688746452332},
 '179': {'16322674': 0.8732975125312805,
  '27123743': 0.8655874133110046,
  '17450673': 0.8492097854614258,
  '5487448': 0.8347427845001221,
  '23557241': 0.8184207677841187,
  '13831842': 0.8049781322479248,
  '13765757': 0.800462543964386,
  '37480103': 0.7954374551773071,
  '16098747': 0.7743245363235474,
  '4828631': 0.7729878425598145},
 '180': {'16966326': 0.8159761428833008,
  '9217800': 0.7307943105697632,
  '13380011': 0.7108882665634155,
  '4889228': 0.702349066734314,
  '6636088': 0.698850154876709,
  '2601324': 0.6966307163238525,
  '41644178': 0.6860047578811646,
  '4407385': 0.6853055953979492,
  '4459491': 0.676759660243988,
  '33911859': 0.6749942302703857},
 '183': {'12827098': 0.7938952445983887,
  '7521113': 0.761419415473938,
  '22406695': 0.7611364126205444,
  '22973574': 0.7578856945037842,
  '10078024': 0.7433014512062073,
  '2192419': 0.7420939803123474,
  '1122198': 0.738577127456665,
  '46193388': 0.7373446822166443,
  '188911': 0.7355397939682007,
  '3495456': 0.734664797782898},
 '185': {'18340282': 0.7271242141723633,
  '22975806': 0.714329719543457,
  '17450673': 0.7112396955490112,
  '27123743': 0.7059183120727539,
  '16322674': 0.7052946090698242,
  '23557241': 0.7026040554046631,
  '13519661': 0.7014828324317932,
  '1866911': 0.7014631628990173,
  '13007205': 0.6993932723999023,
  '2015126': 0.6987407207489014},
 '198': {'13778710': 0.6318005919456482,
  '22191759': 0.6281140446662903,
  '24384587': 0.6273326277732849,
  '857189': 0.6272834539413452,
  '4391121': 0.6270790100097656,
  '19799455': 0.6267902851104736,
  '2177022': 0.6257424354553223,
  '18662787': 0.6248819828033447,
  '17934603': 0.6234248876571655,
  '22198971': 0.62213534116745},
 '208': {'13519661': 0.7683683633804321,
  '22509015': 0.6684942245483398,
  '22975806': 0.6614099144935608,
  '42731834': 0.6608213186264038,
  '17648235': 0.66020667552948,
  '12762485': 0.6547066569328308,
  '3285322': 0.65412837266922,
  '9394119': 0.6532357931137085,
  '18340282': 0.6507447957992554,
  '1780819': 0.6462326049804688},
 '212': {'22038539': 0.7862321138381958,
  '11935250': 0.7853913307189941,
  '42387637': 0.7743264436721802,
  '9291668': 0.7701663970947266,
  '14475235': 0.7699408531188965,
  '4679264': 0.7689058184623718,
  '7808055': 0.7618740797042847,
  '23665162': 0.7562780380249023,
  '4434951': 0.7560144662857056,
  '663464': 0.7465330362319946},
 '213': {'20887554': 0.8594305515289307,
  '27054878': 0.8589242696762085,
  '21048969': 0.7837117910385132,
  '9846940': 0.7609818577766418,
  '2391552': 0.7483125925064087,
  '13625993': 0.7306990027427673,
  '5558754': 0.7292346358299255,
  '25300664': 0.7024550437927246,
  '25028913': 0.6992149949073792,
  '9334631': 0.698915958404541},
 '216': {'21366394': 0.8444218039512634,
  '13923140': 0.738960325717926,
  '1855679': 0.7374188899993896,
  '6123924': 0.7285221219062805,
  '4561402': 0.7217429876327515,
  '1550937': 0.7203171849250793,
  '9160947': 0.7162293791770935,
  '17463549': 0.7065099477767944,
  '14492339': 0.7054212093353271,
  '22198971': 0.705065131187439},
 '217': {'21366394': 0.8405855298042297,
  '1855679': 0.7377536296844482,
  '6123924': 0.7322742342948914,
  '14492339': 0.7155547142028809,
  '17463549': 0.7143187522888184,
  '13923140': 0.7139540910720825,
  '1550937': 0.7102084159851074,
  '9160947': 0.7012363076210022,
  '22198971': 0.700150728225708,
  '6767271': 0.6991226077079773},
 '218': {'21366394': 0.8589640259742737,
  '883747': 0.7744719386100769,
  '26068103': 0.751170814037323,
  '696006': 0.7485990524291992,
  '1800734': 0.7302528619766235,
  '20311968': 0.7295335531234741,
  '1855679': 0.727916955947876,
  '7281161': 0.726165771484375,
  '56486733': 0.7177329063415527,
  '40312663': 0.7143441438674927},
 '219': {'21366394': 0.8628180027008057,
  '883747': 0.7763761281967163,
  '20311968': 0.7512969970703125,
  '26068103': 0.750853955745697,
  '696006': 0.739558219909668,
  '7281161': 0.729993462562561,
  '1800734': 0.729102611541748,
  '56486733': 0.7199928760528564,
  '13923140': 0.7191352248191833,
  '1855679': 0.7181894183158875},
 '230': {'3067015': 0.7608888149261475,
  '32481310': 0.6944716572761536,
  '71625969': 0.6884934902191162,
  '38028419': 0.6807036399841309,
  '5939172': 0.6791460514068604,
  '27408104': 0.6747932434082031,
  '52072815': 0.6702091097831726,
  '849771': 0.6701509356498718,
  '27889071': 0.6562464833259583,
  '19487477': 0.6561838984489441},
 '232': {'10536636': 0.8259591460227966,
  '7655029': 0.8185022473335266,
  '29090823': 0.7961316108703613,
  '457630': 0.6688282489776611,
  '25938221': 0.6469200849533081,
  '8298120': 0.6176676750183105,
  '9167230': 0.609125018119812,
  '1215116': 0.6061424612998962,
  '34818263': 0.6015998125076294,
  '21914176': 0.6007742881774902},
 '233': {'4388470': 0.8540283441543579,
  '41380943': 0.7365560531616211,
  '12232678': 0.7340355515480042,
  '28390999': 0.7302740812301636,
  '16963081': 0.7204646468162537,
  '40971746': 0.7107304334640503,
  '28928964': 0.6937072277069092,
  '3823862': 0.6919922828674316,
  '23581096': 0.6814182996749878,
  '36708463': 0.667527437210083},
 '236': {'4388470': 0.8683549761772156,
  '28390999': 0.7334067821502686,
  '41380943': 0.7310482263565063,
  '12232678': 0.7233695983886719,
  '16963081': 0.7106009125709534,
  '40971746': 0.7055437564849854,
  '28928964': 0.6984655261039734,
  '23581096': 0.6820347905158997,
  '3823862': 0.6765808463096619,
  '27279525': 0.6735905408859253},
 '237': {'12881593': 0.8152358531951904,
  '4942718': 0.807822048664093,
  '34386619': 0.7777997851371765,
  '12824568': 0.7104288339614868,
  '21383026': 0.7056652307510376,
  '31844040': 0.704238772392273,
  '21943141': 0.6957229971885681,
  '17416520': 0.6935610771179199,
  '24706198': 0.6933605670928955,
  '14402338': 0.6923513412475586},
 '238': {'1748921': 0.7553837299346924,
  '18421962': 0.7468637228012085,
  '4463811': 0.7430524230003357,
  '2000038': 0.7405326962471008,
  '8006440': 0.739421546459198,
  '23017040': 0.7244534492492676,
  '13036442': 0.7238221764564514,
  '12014458': 0.7169328927993774,
  '2251426': 0.7166763544082642,
  '2460304': 0.7146047353744507},
 '239': {'2466614': 0.7500429153442383,
  '16693950': 0.7462469339370728,
  '19343151': 0.7440515756607056,
  '3230557': 0.7436604499816895,
  '9559146': 0.7388201355934143,
  '25419778': 0.7310963869094849,
  '4326318': 0.7310277223587036,
  '516867': 0.726799488067627,
  '7834603': 0.7264657616615295,
  '3623127': 0.725522518157959},
 '248': {'1568684': 0.8163108825683594,
  '36033696': 0.6892162561416626,
  '12994780': 0.688923716545105,
  '23369842': 0.6835378408432007,
  '25050364': 0.6795392036437988,
  '36889513': 0.6769522428512573,
  '28845338': 0.6760579347610474,
  '12280462': 0.6758956909179688,
  '4841908': 0.6753995418548584,
  '10883736': 0.6737324595451355},
 '249': {'1568684': 0.8036432266235352,
  '23369842': 0.6839925050735474,
  '36033696': 0.6826905608177185,
  '12280462': 0.6798348426818848,

In [54]:
def retrieve_docs_for_original():
    original_dict = {}
    for i, row in queries_df.iterrows():
        query_embedding = embed_query(row['query_text'])
        scores, indices = index.search(query_embedding, k=10)
        
        print(f"Retrieved Docs for Query ID: {row['query_id']}")
        
        docs_list = []
        
        for rank, idx in enumerate(indices[0], start=1):
            doc_info = {
                'rank': rank,
                'score': scores[0][rank - 1],
                'doc_id': corpus_df.iloc[idx]["index"]
            }
            docs_list.append(doc_info)
        
        original_dict[row['query_id']] = docs_list    
    return original_dict

original_dict = retrieve_docs_for_original()

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 1

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.39it/s]

Retrieved Docs for Query ID: 3

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.63it/s]

Retrieved Docs for Query ID: 5

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 13

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.88it/s]

Retrieved Docs for Query ID: 36

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.91it/s]

Retrieved Docs for Query ID: 42

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 48

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.25it/s]

Retrieved Docs for Query ID: 49

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 50

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.56it/s]

Retrieved Docs for Query ID: 51

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 53

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 54

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28it/s]

Retrieved Docs for Query ID: 56

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.82it/s]

Retrieved Docs for Query ID: 57

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 70

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 72

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.70it/s]

Retrieved Docs for Query ID: 75

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 94

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.67it/s]

Retrieved Docs for Query ID: 99

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.66it/s]

Retrieved Docs for Query ID: 100

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.85it/s]

Retrieved Docs for Query ID: 113

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 115

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 118

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.82it/s]

Retrieved Docs for Query ID: 124

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.09it/s]

Retrieved Docs for Query ID: 127

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 128

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 129

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.91it/s]

Retrieved Docs for Query ID: 130

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.83it/s]

Retrieved Docs for Query ID: 132

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.67it/s]

Retrieved Docs for Query ID: 133

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 137

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.74it/s]

Retrieved Docs for Query ID: 141

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.93it/s]

Retrieved Docs for Query ID: 142

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 143

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.38it/s]

Retrieved Docs for Query ID: 146

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.73it/s]

Retrieved Docs for Query ID: 148

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 163

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 171

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 179

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 180

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 183

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 185

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 198

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.71it/s]

Retrieved Docs for Query ID: 208

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 212

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]

Retrieved Docs for Query ID: 213

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 216

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.93it/s]

Retrieved Docs for Query ID: 217

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 218

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.39it/s]

Retrieved Docs for Query ID: 219

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 230

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 232

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 233

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 236

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 237

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 238

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 239

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 248

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 249

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 261

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.27it/s]

Retrieved Docs for Query ID: 268

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.74it/s]

Retrieved Docs for Query ID: 269

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.93it/s]

Retrieved Docs for Query ID: 274

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 275

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 279

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.40it/s]

Retrieved Docs for Query ID: 294

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 295

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 298

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.34it/s]

Retrieved Docs for Query ID: 300

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]

Retrieved Docs for Query ID: 303

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 312

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.16it/s]

Retrieved Docs for Query ID: 314

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 324

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 327

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]

Retrieved Docs for Query ID: 338

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 343

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 350

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28it/s]

Retrieved Docs for Query ID: 354

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 362

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.76it/s]

Retrieved Docs for Query ID: 380

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 384

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 385

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 386

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.37it/s]

Retrieved Docs for Query ID: 388

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.51it/s]

Retrieved Docs for Query ID: 399

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 410

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 411

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.85it/s]

Retrieved Docs for Query ID: 415

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 421

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 431

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 436

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 437

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.67it/s]

Retrieved Docs for Query ID: 439

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13it/s]

Retrieved Docs for Query ID: 440

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 443

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 452

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 475

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 478

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.83it/s]

Retrieved Docs for Query ID: 491

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.48it/s]

Retrieved Docs for Query ID: 501

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 502

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 507

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 508

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 513

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.47it/s]

Retrieved Docs for Query ID: 514

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 516

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 517

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 521

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.08it/s]

Retrieved Docs for Query ID: 525

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 527

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.64it/s]

Retrieved Docs for Query ID: 528

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 532

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.60it/s]

Retrieved Docs for Query ID: 533

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.60it/s]

Retrieved Docs for Query ID: 535

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 536

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 539

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 540

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.41it/s]

Retrieved Docs for Query ID: 544

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 549

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.16it/s]

Retrieved Docs for Query ID: 551

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 552

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.51it/s]

Retrieved Docs for Query ID: 554

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86it/s]

Retrieved Docs for Query ID: 560

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.71it/s]

Retrieved Docs for Query ID: 569

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.85it/s]

Retrieved Docs for Query ID: 575

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 577

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 578

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 587

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 589

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 593

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13it/s]

Retrieved Docs for Query ID: 597

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 598

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.67it/s]

Retrieved Docs for Query ID: 613

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86it/s]

Retrieved Docs for Query ID: 619

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 623

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 628

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.73it/s]

Retrieved Docs for Query ID: 636

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]

Retrieved Docs for Query ID: 637

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 641

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 644

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 649

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.36it/s]

Retrieved Docs for Query ID: 659

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 660

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 674

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 684

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.71it/s]

Retrieved Docs for Query ID: 690

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.94it/s]

Retrieved Docs for Query ID: 691

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 692

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 693

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 700

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86it/s]

Retrieved Docs for Query ID: 702

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 715

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 716

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 718

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.53it/s]

Retrieved Docs for Query ID: 721

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 723

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.83it/s]

Retrieved Docs for Query ID: 727

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 728

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 729

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 742

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 743

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 744

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 756

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.64it/s]

Retrieved Docs for Query ID: 759

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13it/s]

Retrieved Docs for Query ID: 768

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.70it/s]

Retrieved Docs for Query ID: 770

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 775

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28it/s]

Retrieved Docs for Query ID: 781

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 783

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 784

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.33it/s]

Retrieved Docs for Query ID: 785

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 793

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 800

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 805

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 808

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 811

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.51it/s]

Retrieved Docs for Query ID: 814

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 820

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 821

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 823

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.83it/s]

Retrieved Docs for Query ID: 830

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.70it/s]

Retrieved Docs for Query ID: 831

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 832

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]

Retrieved Docs for Query ID: 834

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 837

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 839

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 845

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]

Retrieved Docs for Query ID: 847

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.39it/s]

Retrieved Docs for Query ID: 852

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 859

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 870

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.63it/s]

Retrieved Docs for Query ID: 873

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 879

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.71it/s]

Retrieved Docs for Query ID: 880

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 882

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.39it/s]

Retrieved Docs for Query ID: 887

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 903

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.34it/s]

Retrieved Docs for Query ID: 904

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.16it/s]

Retrieved Docs for Query ID: 907

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 911

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 913

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 914

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 921

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 922

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 936

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]

Retrieved Docs for Query ID: 956

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 957

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 960

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 967

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 971

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 975

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.98it/s]

Retrieved Docs for Query ID: 982

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.16it/s]

Retrieved Docs for Query ID: 985

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.99it/s]

Retrieved Docs for Query ID: 993

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 1012

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 1014

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.00it/s]

Retrieved Docs for Query ID: 1019

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 1020

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.67it/s]

Retrieved Docs for Query ID: 1021

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1024

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13it/s]

Retrieved Docs for Query ID: 1029

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 1041

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 1049

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.94it/s]

Retrieved Docs for Query ID: 1062

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13it/s]

Retrieved Docs for Query ID: 1086

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.83it/s]

Retrieved Docs for Query ID: 1088

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 1089

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.37it/s]

Retrieved Docs for Query ID: 1099

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 1100

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 1104

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1107

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.27it/s]

Retrieved Docs for Query ID: 1110

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 1121

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 1130

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.67it/s]

Retrieved Docs for Query ID: 1132

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 1137

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86it/s]

Retrieved Docs for Query ID: 1140

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 1144

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.83it/s]

Retrieved Docs for Query ID: 1146

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86it/s]

Retrieved Docs for Query ID: 1150

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 1163

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.41it/s]

Retrieved Docs for Query ID: 1175

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 1179

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.74it/s]

Retrieved Docs for Query ID: 1180

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 1185

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 1187

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.41it/s]

Retrieved Docs for Query ID: 1191

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.63it/s]

Retrieved Docs for Query ID: 1194

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1196

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1197

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.98it/s]

Retrieved Docs for Query ID: 1199

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08it/s]

Retrieved Docs for Query ID: 1200

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 1202

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 1204

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.76it/s]

Retrieved Docs for Query ID: 1207

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 1213

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 1216

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 1221

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1225

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 1226

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.95it/s]

Retrieved Docs for Query ID: 1232

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54it/s]

Retrieved Docs for Query ID: 1241

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 1245

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 1259

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 1262

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 1266

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 1270

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 1271

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.90it/s]

Retrieved Docs for Query ID: 1272

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39it/s]

Retrieved Docs for Query ID: 1273

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.76it/s]

Retrieved Docs for Query ID: 1274

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.63it/s]

Retrieved Docs for Query ID: 1278

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.66it/s]

Retrieved Docs for Query ID: 1279

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]

Retrieved Docs for Query ID: 1280

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.42it/s]

Retrieved Docs for Query ID: 1281

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13it/s]

Retrieved Docs for Query ID: 1282

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 1290

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 1292

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.87it/s]

Retrieved Docs for Query ID: 1298

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.28it/s]

Retrieved Docs for Query ID: 1303

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1316

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1319

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.70it/s]

Retrieved Docs for Query ID: 1320

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.49it/s]

Retrieved Docs for Query ID: 1332

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.24it/s]

Retrieved Docs for Query ID: 1335

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.28it/s]

Retrieved Docs for Query ID: 1336

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 1337

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.87it/s]

Retrieved Docs for Query ID: 1339

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.62it/s]

Retrieved Docs for Query ID: 1344

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 1352

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Retrieved Docs for Query ID: 1359

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 1362

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 1363

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

Retrieved Docs for Query ID: 1368

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.11it/s]

Retrieved Docs for Query ID: 1370

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86it/s]

Retrieved Docs for Query ID: 1379

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]

Retrieved Docs for Query ID: 1382

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23it/s]

Retrieved Docs for Query ID: 1385

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18it/s]

Retrieved Docs for Query ID: 1389

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.92it/s]

Retrieved Docs for Query ID: 1395

In [55]:
original_dict

{'1': [{'rank': 1, 'score': np.float32(0.74253714), 'doc_id': '4346436'},
  {'rank': 2, 'score': np.float32(0.72045124), 'doc_id': '17388232'},
  {'rank': 3, 'score': np.float32(0.70520407), 'doc_id': '16962732'},
  {'rank': 4, 'score': np.float32(0.700097), 'doc_id': '29638116'},
  {'rank': 5, 'score': np.float32(0.69810796), 'doc_id': '927561'},
  {'rank': 6, 'score': np.float32(0.6949593), 'doc_id': '21456232'},
  {'rank': 7, 'score': np.float32(0.6948125), 'doc_id': '23763738'},
  {'rank': 8, 'score': np.float32(0.6910435), 'doc_id': '2121272'},
  {'rank': 9, 'score': np.float32(0.6909677), 'doc_id': '14103509'},
  {'rank': 10, 'score': np.float32(0.6894997), 'doc_id': '16736872'}],
 '3': [{'rank': 1, 'score': np.float32(0.71154726), 'doc_id': '4414547'},
  {'rank': 2, 'score': np.float32(0.7090507), 'doc_id': '10944947'},
  {'rank': 3, 'score': np.float32(0.6994143), 'doc_id': '19058822'},
  {'rank': 4, 'score': np.float32(0.6966059), 'doc_id': '23389795'},
  {'rank': 5, 'score': np.float32(0.6939852), 'doc_id': '14717500'},
  {'rank': 6, 'score': np.float32(0.6827147), 'doc_id': '2739854'},
  {'rank': 7, 'score': np.float32(0.6799712), 'doc_id': '4632921'},
  {'rank': 8, 'score': np.float32(0.67671806), 'doc_id': '10145528'},
  {'rank': 9, 'score': np.float32(0.67382276), 'doc_id': '3823862'},
  {'rank': 10, 'score': np.float32(0.6707893), 'doc_id': '13791788'}],
 '5': [{'rank': 1, 'score': np.float32(0.7466669), 'doc_id': '13734012'},
  {'rank': 2, 'score': np.float32(0.7285504), 'doc_id': '27063470'},
  {'rank': 3, 'score': np.float32(0.68321407), 'doc_id': '25261168'},
  {'rank': 4, 'score': np.float32(0.667337), 'doc_id': '18617259'},
  {'rank': 5, 'score': np.float32(0.6667924), 'doc_id': '23124332'},
  {'rank': 6, 'score': np.float32(0.66478145), 'doc_id': '11349166'},
  {'rank': 7, 'score': np.float32(0.6647285), 'doc_id': '21550246'},
  {'rank': 8, 'score': np.float32(0.6593499), 'doc_id': '1583041'},
  {'rank': 9, 'score': np.float32(0.6496787), 'doc_id': '841371'},
  {'rank': 10, 'score': np.float32(0.6411488), 'doc_id': '19945096'}],
 '13': [{'rank': 1, 'score': np.float32(0.7227812), 'doc_id': '7662395'},
  {'rank': 2, 'score': np.float32(0.7146446), 'doc_id': '4791384'},
  {'rank': 3, 'score': np.float32(0.71082395), 'doc_id': '1263446'},
  {'rank': 4, 'score': np.float32(0.70996296), 'doc_id': '16204011'},
  {'rank': 5, 'score': np.float32(0.70121014), 'doc_id': '33257464'},
  {'rank': 6, 'score': np.float32(0.69623834), 'doc_id': '1606628'},
  {'rank': 7, 'score': np.float32(0.6942602), 'doc_id': '8529693'},
  {'rank': 8, 'score': np.float32(0.6920365), 'doc_id': '13791044'},
  {'rank': 9, 'score': np.float32(0.68740505), 'doc_id': '28633594'},
  {'rank': 10, 'score': np.float32(0.68711275), 'doc_id': '30786800'}],
 '36': [{'rank': 1, 'score': np.float32(0.7585161), 'doc_id': '18557974'},
  {'rank': 2, 'score': np.float32(0.7392795), 'doc_id': '37424881'},
  {'rank': 3, 'score': np.float32(0.73546076), 'doc_id': '21636085'},
  {'rank': 4, 'score': np.float32(0.73500717), 'doc_id': '11705328'},
  {'rank': 5, 'score': np.float32(0.7305281), 'doc_id': '3215494'},
  {'rank': 6, 'score': np.float32(0.7269996), 'doc_id': '33409100'},
  {'rank': 7, 'score': np.float32(0.72590923), 'doc_id': '10557471'},
  {'rank': 8, 'score': np.float32(0.7229295), 'doc_id': '13801259'},
  {'rank': 9, 'score': np.float32(0.7208736), 'doc_id': '18256197'},
  {'rank': 10, 'score': np.float32(0.7076902), 'doc_id': '16252863'}],
 '42': [{'rank': 1, 'score': np.float32(0.8372566), 'doc_id': '18174210'},
  {'rank': 2, 'score': np.float32(0.8024379), 'doc_id': '27889071'},
  {'rank': 3, 'score': np.float32(0.7766601), 'doc_id': '40913091'},
  {'rank': 4, 'score': np.float32(0.73325086), 'doc_id': '32481310'},
  {'rank': 5, 'score': np.float32(0.72544485), 'doc_id': '24042919'},
  {'rank': 6, 'score': np.float32(0.72460747), 'doc_id': '45218443'},
  {'rank': 7, 'score': np.float32(0.7214228), 'doc_id': '1145473'},
  {'rank': 8, 'score': np.float32(0.7100602), 'doc_id': '6315132'},
  {'rank': 9, 'score': np.float32(0.704798), 'doc_id': '13959707'},
  {'rank': 10, 'score': np.float32(0.6948476), 'doc_id': '8083310'}],
 '48': [{'rank': 1, 'score': np.float32(0.7429801), 'doc_id': '27063470'},
  {'rank': 2, 'score': np.float32(0.7341349), 'doc_id': '11349166'},
  {'rank': 3, 'score': np.float32(0.68308806), 'doc_id': '23203102'},
  {'rank': 4, 'score': np.float32(0.68240726), 'doc_id': '13734012'},
  {'rank': 5, 'score': np.float32(0.67325544), 'doc_id': '29955650'},
  {'rank': 6, 'score': np.float32(0.6631237), 'doc_id': '18617259'},
  {'rank': 7, 'score': np.float32(0.6605445), 'doc_id': '5850219'},
  {'rank': 8, 'score': np.float32(0.6514443), 'doc_id': '3413083'},
  {'rank': 9, 'score': np.float32(0.64557755), 'doc_id': '22194407'},
  {'rank': 10, 'score': np.float32(0.6368613), 'doc_id': '25261168'}],
 '49': [{'rank': 1, 'score': np.float32(0.8590019), 'doc_id': '5953485'},
  {'rank': 2, 'score': np.float32(0.7774028), 'doc_id': '5702790'},
  {'rank': 3, 'score': np.float32(0.7605112), 'doc_id': '7029990'},
  {'rank': 4, 'score': np.float32(0.7585821), 'doc_id': '23913146'},
  {'rank': 5, 'score': np.float32(0.7346342), 'doc_id': '8006440'},
  {'rank': 6, 'score': np.float32(0.72959846), 'doc_id': '22362025'},
  {'rank': 7, 'score': np.float32(0.72717774), 'doc_id': '5409325'},
  {'rank': 8, 'score': np.float32(0.7267639), 'doc_id': '12652963'},
  {'rank': 9, 'score': np.float32(0.7145686), 'doc_id': '1333643'},
  {'rank': 10, 'score': np.float32(0.7139209), 'doc_id': '86602746'}],
 '50': [{'rank': 1, 'score': np.float32(0.77787524), 'doc_id': '12580014'},
  {'rank': 2, 'score': np.float32(0.7338417), 'doc_id': '25738896'},
  {'rank': 3, 'score': np.float32(0.7245697), 'doc_id': '18488986'},
  {'rank': 4, 'score': np.float32(0.70212793), 'doc_id': '19736671'},
  {'rank': 5, 'score': np.float32(0.6983601), 'doc_id': '13989491'},
  {'rank': 6, 'score': np.float32(0.695377), 'doc_id': '36950726'},
  {'rank': 7, 'score': np.float32(0.69395155), 'doc_id': '29785642'},
  {'rank': 8, 'score': np.float32(0.69194853), 'doc_id': '19343151'},
  {'rank': 9, 'score': np.float32(0.68289113), 'doc_id': '39559521'},
  {'rank': 10, 'score': np.float32(0.6808554), 'doc_id': '15405204'}],
 '51': [{'rank': 1, 'score': np.float32(0.8598312), 'doc_id': '45638119'},
  {'rank': 2, 'score': np.float32(0.73280597), 'doc_id': '24349992'},
  {'rank': 3, 'score': np.float32(0.72512585), 'doc_id': '1866911'},
  {'rank': 4, 'score': np.float32(0.70839083), 'doc_id': '36212758'},
  {'rank': 5, 'score': np.float32(0.7025745), 'doc_id': '14663842'},
  {'rank': 6, 'score': np.float32(0.7021649), 'doc_id': '43385013'},
  {'rank': 7, 'score': np.float32(0.70149124), 'doc_id': '17648235'},
  {'rank': 8, 'score': np.float32(0.7011577), 'doc_id': '3067015'},
  {'rank': 9, 'score': np.float32(0.7007107), 'doc_id': '4886637'},
  {'rank': 10, 'score': np.float32(0.7005287), 'doc_id': '31311495'}],
 '53': [{'rank': 1, 'score': np.float32(0.8587987), 'doc_id': '45638119'},
  {'rank': 2, 'score': np.float32(0.7261655), 'doc_id': '24349992'},
  {'rank': 3, 'score': np.float32(0.7247665), 'doc_id': '1866911'},
  {'rank': 4, 'score': np.float32(0.7205417), 'doc_id': '15113221'},
  {'rank': 5, 'score': np.float32(0.71766627), 'doc_id': '4418878'},
  {'rank': 6, 'score': np.float32(0.7171635), 'doc_id': '6517763'},
  {'rank': 7, 'score': np.float32(0.71190715), 'doc_id': '12762485'},
  {'rank': 8, 'score': np.float32(0.7112442), 'doc_id': '36212758'},
  {'rank': 9, 'score': np.float32(0.7093143), 'doc_id': '7228140'},
  {'rank': 10, 'score': np.float32(0.7083583), 'doc_id': '43385013'}],
 '54': [{'rank': 1, 'score': np.float32(0.8628293), 'doc_id': '49556906'},
  {'rank': 2, 'score': np.float32(0.7938494), 'doc_id': '3973445'},
  {'rank': 3, 'score': np.float32(0.773335), 'doc_id': '3419709'},
  {'rank': 4, 'score': np.float32(0.7717631), 'doc_id': '24721866'},
  {'rank': 5, 'score': np.float32(0.7589005), 'doc_id': '32408470'},
  {'rank': 6, 'score': np.float32(0.7557376), 'doc_id': '26025820'},
  {'rank': 7, 'score': np.float32(0.75380504), 'doc_id': '1907601'},
  {'rank': 8, 'score': np.float32(0.75271356), 'doc_id': '7005276'},
  {'rank': 9, 'score': np.float32(0.7492028), 'doc_id': '22621251'},
  {'rank': 10, 'score': np.float32(0.746886), 'doc_id': '1590744'}],
 '56': [{'rank': 1, 'score': np.float32(0.86399066), 'doc_id': '4709641'},
  {'rank': 2, 'score': np.float32(0.77162105), 'doc_id': '4459491'},
  {'rank': 3, 'score': np.float32(0.7708137), 'doc_id': '13814480'},
  {'rank': 4, 'score': np.float32(0.75410485), 'doc_id': '10795063'},
  {'rank': 5, 'score': np.float32(0.7399475), 'doc_id': '31347396'},
  {'rank': 6, 'score': np.float32(0.7390632), 'doc_id': '13293033'},
  {'rank': 7, 'score': np.float32(0.72937715), 'doc_id': '11659421'},
  {'rank': 8, 'score': np.float32(0.72576535), 'doc_id': '30351165'},
  {'rank': 9, 'score': np.float32(0.72462225), 'doc_id': '24725136'},
  {'rank': 10, 'score': np.float32(0.7231977), 'doc_id': '36637129'}],
 '57': [{'rank': 1, 'score': np.float32(0.86327744), 'doc_id': '4709641'},
  {'rank': 2, 'score': np.float32(0.7680787), 'doc_id': '4459491'},
  {'rank': 3, 'score': np.float32(0.7678164), 'doc_id': '13814480'},
  {'rank': 4, 'score': np.float32(0.75481796), 'doc_id': '10795063'},
  {'rank': 5, 'score': np.float32(0.7325914), 'doc_id': '13293033'},
  {'rank': 6, 'score': np.float32(0.73066163), 'doc_id': '36637129'},
  {'rank': 7, 'score': np.float32(0.7295614), 'doc_id': '31347396'},
  {'rank': 8, 'score': np.float32(0.729185), 'doc_id': '30351165'},
  {'rank': 9, 'score': np.float32(0.7257409), 'doc_id': '11659421'},
  {'rank': 10, 'score': np.float32(0.7189619), 'doc_id': '1964163'}],
 '70': [{'rank': 1, 'score': np.float32(0.78618187), 'doc_id': '4414547'},
  {'rank': 2, 'score': np.float32(0.7666184), 'doc_id': '11903247'},
  {'rank': 3, 'score': np.float32(0.76654863), 'doc_id': '5956380'},
  {'rank': 4, 'score': np.float32(0.7640258), 'doc_id': '31624828'},
  {'rank': 5, 'score': np.float32(0.75287116), 'doc_id': '7225911'},
  {'rank': 6, 'score': np.float32(0.750954), 'doc_id': '21557055'},
  {'rank': 7, 'score': np.float32(0.747499), 'doc_id': '9483851'},
  {'rank': 8, 'score': np.float32(0.73814404), 'doc_id': '12240507'},
  {'rank': 9, 'score': np.float32(0.7373251), 'doc_id': '2582169'},
  {'rank': 10, 'score': np.float32(0.736439), 'doc_id': '36464673'}],
 '72': [{'rank': 1, 'score': np.float32(0.70256114), 'doc_id': '24335068'},
  {'rank': 2, 'score': np.float32(0.70101154), 'doc_id': '14296612'},
  {'rank': 3, 'score': np.float32(0.6991432), 'doc_id': '2119889'},
  {'rank': 4, 'score': np.float32(0.6985542), 'doc_id': '6076903'},
  {'rank': 5, 'score': np.float32(0.69719636), 'doc_id': '8997410'},
  {'rank': 6, 'score': np.float32(0.69705474), 'doc_id': '18576103'},
  {'rank': 7, 'score': np.float32(0.69155383), 'doc_id': '40383969'},
  {'rank': 8, 'score': np.float32(0.69084114), 'doc_id': '36399109'},
  {'rank': 9, 'score': np.float32(0.68981814), 'doc_id': '9021186'},
  {'rank': 10, 'score': np.float32(0.68822426), 'doc_id': '18895793'}],
 '75': [{'rank': 1, 'score': np.float32(0.8099989), 'doc_id': '4387784'},
  {'rank': 2, 'score': np.float32(0.75478435), 'doc_id': '25657127'},
  {'rank': 3, 'score': np.float32(0.7483002), 'doc_id': '37768883'},
  {'rank': 4, 'score': np.float32(0.74075544), 'doc_id': '29214508'},
  {'rank': 5, 'score': np.float32(0.73902714), 'doc_id': '36233757'},
  {'rank': 6, 'score': np.float32(0.7363798), 'doc_id': '38805486'},
  {'rank': 7, 'score': np.float32(0.70531124), 'doc_id': '13965483'},
  {'rank': 8, 'score': np.float32(0.70063627), 'doc_id': '26488879'},
  {'rank': 9, 'score': np.float32(0.6935349), 'doc_id': '1744752'},
  {'rank': 10, 'score': np.float32(0.68571126), 'doc_id': '12691537'}],
 '94': [{'rank': 1, 'score': np.float32(0.6632222), 'doc_id': '12409683'},
  {'rank': 2, 'score': np.float32(0.6631841), 'doc_id': '18025240'},
  {'rank': 3, 'score': np.float32(0.65308344), 'doc_id': '1215116'},
  {'rank': 4, 'score': np.float32(0.64312947), 'doc_id': '10617916'},
  {'rank': 5, 'score': np.float32(0.6329755), 'doc_id': '1805641'},
  {'rank': 6, 'score': np.float32(0.6272198), 'doc_id': '3929361'},
  {'rank': 7, 'score': np.float32(0.62444645), 'doc_id': '13966946'},
  {'rank': 8, 'score': np.float32(0.6209309), 'doc_id': '18074797'},
  {'rank': 9, 'score': np.float32(0.61476386), 'doc_id': '9110810'},
  {'rank': 10, 'score': np.float32(0.6139978), 'doc_id': '15237660'}],
 '99': [{'rank': 1, 'score': np.float32(0.70526206), 'doc_id': '18810195'},
  {'rank': 2, 'score': np.float32(0.683148), 'doc_id': '13578199'},
  {'rank': 3, 'score': np.float32(0.6813741), 'doc_id': '15795880'},
  {'rank': 4, 'score': np.float32(0.6810177), 'doc_id': '36233757'},
  {'rank': 5, 'score': np.float32(0.67802393), 'doc_id': '4387784'},
  {'rank': 6, 'score': np.float32(0.676906), 'doc_id': '14180217'},
  {'rank': 7, 'score': np.float32(0.6760124), 'doc_id': '12265561'},
  {'rank': 8, 'score': np.float32(0.6749666), 'doc_id': '2617858'},
  {'rank': 9, 'score': np.float32(0.6704247), 'doc_id': '44947611'},
  {'rank': 10, 'score': np.float32(0.66896504), 'doc_id': '4396105'}],
 '100': [{'rank': 1, 'score': np.float32(0.7804166), 'doc_id': '4381486'},
  {'rank': 2, 'score': np.float32(0.7739594), 'doc_id': '14550841'},
  {'rank': 3, 'score': np.float32(0.74070626), 'doc_id': '13980338'},
  {'rank': 4, 'score': np.float32(0.7406901), 'doc_id': '9154703'},
  {'rank': 5, 'score': np.float32(0.73277473), 'doc_id': '11020675'},
  {'rank': 6, 'score': np.float32(0.7298411), 'doc_id': '30152134'},
  {'rank': 7, 'score': np.float32(0.72829944), 'doc_id': '3321943'},
  {'rank': 8, 'score': np.float32(0.727075), 'doc_id': '1381673'},
  {'rank': 9, 'score': np.float32(0.7257419), 'doc_id': '18374364'},
  {'rank': 10, 'score': np.float32(0.7246252), 'doc_id': '4421787'}],
 '113': [{'rank': 1, 'score': np.float32(0.79788756), 'doc_id': '25816994'},
  {'rank': 2, 'score': np.float32(0.7861097), 'doc_id': '6157837'},
  {'rank': 3, 'score': np.float32(0.75721943), 'doc_id': '44030361'},
  {'rank': 4, 'score': np.float32(0.7491171), 'doc_id': '1759213'},
  {'rank': 5, 'score': np.float32(0.7471043), 'doc_id': '3825750'},
  {'rank': 6, 'score': np.float32(0.7459768), 'doc_id': '40790033'},
  {'rank': 7, 'score': np.float32(0.7391132), 'doc_id': '4678846'},
  {'rank': 8, 'score': np.float32(0.7247236), 'doc_id': '26199970'},
  {'rank': 9, 'score': np.float32(0.7197066), 'doc_id': '10072941'},
  {'rank': 10, 'score': np.float32(0.71924174), 'doc_id': '140098548'}],
 '115': [{'rank': 1, 'score': np.float32(0.6853866), 'doc_id': '33872649'},
  {'rank': 2, 'score': np.float32(0.5942935), 'doc_id': '15879544'},
  {'rank': 3, 'score': np.float32(0.57248646), 'doc_id': '4321295'},
  {'rank': 4, 'score': np.float32(0.5639392), 'doc_id': '18855191'},
  {'rank': 5, 'score': np.float32(0.55628085), 'doc_id': '695938'},
  {'rank': 6, 'score': np.float32(0.55496824), 'doc_id': '96222213'},
  {'rank': 7, 'score': np.float32(0.55439544), 'doc_id': '4942718'},
  {'rank': 8, 'score': np.float32(0.55027443), 'doc_id': '12824568'},
  {'rank': 9, 'score': np.float32(0.5484952), 'doc_id': '1234098'},
  {'rank': 10, 'score': np.float32(0.54764056), 'doc_id': '15414628'}],
 '118': [{'rank': 1, 'score': np.float32(0.86850697), 'doc_id': '4465735'},
  {'rank': 2, 'score': np.float32(0.8682952), 'doc_id': '6372244'},
  {'rank': 3, 'score': np.float32(0.7383982), 'doc_id': '32454714'},
  {'rank': 4, 'score': np.float32(0.7274723), 'doc_id': '52805891'},
  {'rank': 5, 'score': np.float32(0.72272456), 'doc_id': '15578265'},
  {'rank': 6, 'score': np.float32(0.7194015), 'doc_id': '4492358'},
  {'rank': 7, 'score': np.float32(0.7127336), 'doc_id': '15274349'},
  {'rank': 8, 'score': np.float32(0.70787394), 'doc_id': '21956124'},
  {'rank': 9, 'score': np.float32(0.7068915), 'doc_id': '34603465'},
  {'rank': 10, 'score': np.float32(0.70560956), 'doc_id': '20148808'}],
 '124': [{'rank': 1, 'score': np.float32(0.85414064), 'doc_id': '4883040'},
  {'rank': 2, 'score': np.float32(0.80462873), 'doc_id': '7111021'},
  {'rank': 3, 'score': np.float32(0.75175583), 'doc_id': '21479231'},
  {'rank': 4, 'score': np.float32(0.7515148), 'doc_id': '31363207'},
  {'rank': 5, 'score': np.float32(0.7432398), 'doc_id': '13899137'},
  {'rank': 6, 'score': np.float32(0.7291391), 'doc_id': '22414304'},
  {'rank': 7, 'score': np.float32(0.72677016), 'doc_id': '14319754'},
  {'rank': 8, 'score': np.float32(0.7223501), 'doc_id': '13914633'},
  {'rank': 9, 'score': np.float32(0.7192606), 'doc_id': '1986482'},
  {'rank': 10, 'score': np.float32(0.7181219), 'doc_id': '13901073'}],
 '127': [{'rank': 1, 'score': np.float32(0.70855564), 'doc_id': '35231675'},
  {'rank': 2, 'score': np.float32(0.69995326), 'doc_id': '21598000'},
  {'rank': 3, 'score': np.float32(0.6966405), 'doc_id': '38623601'},
  {'rank': 4, 'score': np.float32(0.6804295), 'doc_id': '20054396'},
  {'rank': 5, 'score': np.float32(0.67967933), 'doc_id': '23618826'},
  {'rank': 6, 'score': np.float32(0.6778145), 'doc_id': '86231298'},
  {'rank': 7, 'score': np.float32(0.677179), 'doc_id': '39863735'},
  {'rank': 8, 'score': np.float32(0.6760885), 'doc_id': '14178995'},
  {'rank': 9, 'score': np.float32(0.6752335), 'doc_id': '26495128'},
  {'rank': 10, 'score': np.float32(0.67519635), 'doc_id': '12685434'}],
 '128': [{'rank': 1, 'score': np.float32(0.68546915), 'doc_id': '12549585'},
  {'rank': 2, 'score': np.float32(0.6666496), 'doc_id': '79447'},
  {'rank': 3, 'score': np.float32(0.66119087), 'doc_id': '12513972'},
  {'rank': 4, 'score': np.float32(0.6606267), 'doc_id': '5254741'},
  {'rank': 5, 'score': np.float32(0.66026515), 'doc_id': '2260571'},
  {'rank': 6, 'score': np.float32(0.6588856), 'doc_id': '25300664'},
  {'rank': 7, 'score': np.float32(0.65562296), 'doc_id': '19854543'},
  {'rank': 8, 'score': np.float32(0.6523887), 'doc_id': '33569870'},
  {'rank': 9, 'score': np.float32(0.6512444), 'doc_id': '23785605'},
  {'rank': 10, 'score': np.float32(0.6491735), 'doc_id': '17168045'}],
 '129': [{'rank': 1, 'score': np.float32(0.7455553), 'doc_id': '27768226'},
  {'rank': 2, 'score': np.float32(0.6636082), 'doc_id': '6477536'},
  {'rank': 3, 'score': np.float32(0.6320994), 'doc_id': '16979690'},
  {'rank': 4, 'score': np.float32(0.62653077), 'doc_id': '39652608'},
  {'rank': 5, 'score': np.float32(0.6131314), 'doc_id': '4688277'},
  {'rank': 6, 'score': np.float32(0.59974515), 'doc_id': '6319826'},
  {'rank': 7, 'score': np.float32(0.59730494), 'doc_id': '790598'},
  {'rank': 8, 'score': np.float32(0.5913737), 'doc_id': '7547329'},
  {'rank': 9, 'score': np.float32(0.58884263), 'doc_id': '22711954'},
  {'rank': 10, 'score': np.float32(0.57520294), 'doc_id': '14319754'}],
 '130': [{'rank': 1, 'score': np.float32(0.7843082), 'doc_id': '27768226'},
  {'rank': 2, 'score': np.float32(0.641279), 'doc_id': '6477536'},
  {'rank': 3, 'score': np.float32(0.6400316), 'doc_id': '16979690'},
  {'rank': 4, 'score': np.float32(0.62993526), 'doc_id': '39652608'},
  {'rank': 5, 'score': np.float32(0.62621343), 'doc_id': '4688277'},
  {'rank': 6, 'score': np.float32(0.6095117), 'doc_id': '22711954'},
  {'rank': 7, 'score': np.float32(0.6060895), 'doc_id': '6319826'},
  {'rank': 8, 'score': np.float32(0.60541576), 'doc_id': '790598'},
  {'rank': 9, 'score': np.float32(0.5948249), 'doc_id': '7547329'},
  {'rank': 10, 'score': np.float32(0.59033847), 'doc_id': '26532518'}],
 '132': [{'rank': 1, 'score': np.float32(0.72353387), 'doc_id': '15648443'},
  {'rank': 2, 'score': np.float32(0.7180096), 'doc_id': '3866315'},
  {'rank': 3, 'score': np.float32(0.71791345), 'doc_id': '39903312'},
  {'rank': 4, 'score': np.float32(0.7168051), 'doc_id': '2443495'},
  {'rank': 5, 'score': np.float32(0.7139677), 'doc_id': '9159125'},
  {'rank': 6, 'score': np.float32(0.7130596), 'doc_id': '6407356'},

In [57]:
from ranx import Qrels, Run, evaluate

results = evaluate(
    qrels,
    run_dict,
    [
        "recall@5",
        "recall@10",
        "mrr@10",
        "ndcg@10"
    ]
)

In [58]:
print(results)

{'recall@5': np.float64(0.8142777777777778), 'recall@10': np.float64(0.8668888888888889), 'mrr@10': np.float64(0.7129867724867726), 'ndcg@10': np.float64(0.7469604744966187)}

In [32]:
import pandas as pd
from ranx import Qrels, Run, evaluate

# Create Qrels and Run objects
qrels_obj = Qrels(qrels)
run_obj = Run(run_dict)

# Get overall results
overall_results = evaluate(
    qrels_obj,
    run_obj,
    ["recall@5", "recall@10", "mrr@10", "ndcg@10"]
)

# Get per-query results by iterating over each query
per_query_results = {}

for query_id in qrels.keys():
    if query_id in run_dict:
        # Create single-query Qrels and Run
        single_qrels = Qrels({query_id: qrels[query_id]})
        single_run = Run({query_id: run_dict[query_id]})
        
        # Evaluate for this single query
        single_results = evaluate(
            single_qrels,
            single_run,
            ["recall@5", "recall@10", "mrr@10", "ndcg@10"]
        )
        
        per_query_results[query_id] = single_results

df_per_query = pd.DataFrame(per_query_results).T
df_per_query.index.name = 'query_id'
df_per_query = df_per_query.reset_index()

In [34]:
df_per_query

    query_id  recall@5  recall@10    mrr@10   ndcg@10
0          1       0.0        0.0  0.000000  0.000000
1          3       1.0        1.0  0.200000  0.386853
2          5       1.0        1.0  1.000000  1.000000
3         13       0.0        1.0  0.166667  0.356207
4         36       0.5        0.5  0.250000  0.264068
..       ...       ...        ...       ...       ...
295     1379       1.0        1.0  1.000000  1.000000
296     1382       1.0        1.0  1.000000  1.000000
297     1385       1.0        1.0  1.000000  1.000000
298     1389       1.0        1.0  1.000000  1.000000
299     1395       1.0        1.0  0.333333  0.500000

[300 rows x 5 columns]

# Direct query expansion using LLM

I decided to use gemini-3.5-flash using the api

My pipeline do far is : first to do a Direct query expansion and then a Pseudo-document expansion / HyDE-style using the LLM.

SciFact query
      │
      ├──────────────────────┐
      │                      │
      ▼                      ▼
Original query          LLM expansion
      │                      │
      │                 Expanded query
      │                      │
      ▼                      ▼
     BGE                    BGE
      │                      │
      ▼                      ▼
   FAISS                  FAISS
      │                      │
      ▼                      ▼
 Original Run           Expanded Run
      │                      │
      └──────────┬───────────┘
                 ▼
          ranx evaluation
                 │
       Recall / MRR / nDCG

In [ ]:
import os
import google.generativeai as genai
genai.configure(api_key=os.environ["GEMINI_API_KEY"])
model = genai.GenerativeModel('gemini-3.5-flash')

Original query
      ↓
     LLM
      ↓
Expanded query (plain text)
      ↓
BGE encoder
      ↓
Dense retrieval

In [35]:
EXPANSION_PROMPT = """
You are an information retrieval query expansion system.

Your task is to generate a small set of expansion terms or short phrases
for a scientific search query used in dense document retrieval.

Generate ONLY additional terms or short phrases that express the SAME
concepts already present in the original query.

You may add:
- direct synonyms
- abbreviations
- alternative scientific terminology
- equivalent scientific terms or phrases

Do NOT add:
- broader concepts
- narrower or specific subtypes not explicitly mentioned
- consequences or effects
- applications
- examples
- related but distinct concepts
- new facts or information
- terms that change or reinterpret the original claim
- unnecessary or redundant terms

IMPORTANT:
- Do NOT rewrite the original query.
- Do NOT generate a new query or sentence.
- Do NOT repeat the original query.
- Do NOT explain anything.
- Generate ONLY the additional expansion terms or short phrases.
- Keep the expansion concise.
- Generate at most 5-8 terms or short phrases.
- Prefer scientifically meaningful multi-word phrases when appropriate.
- Return the terms or phrases separated by commas.

The original query will be preserved separately and automatically concatenated
with your output. Therefore, you must NOT include the original query in your output.

Original query:
{query}
"""

In [36]:
import time

def expand_query(query, max_retries=5):
    """Expand a search query using Gemini"""
    prompt = EXPANSION_PROMPT.format(query=query)
    
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            return response.text.strip()
            
        except Exception as e:
            print(f"Error on attempt {attempt + 1}: {e}")
            
            if attempt < max_retries - 1:
                wait_time = 2 ** attempt
                print(f"Retrying in {wait_time} seconds...")
                time.sleep(wait_time)
            else:
                print("Maximum retries reached. Returning None.")
                return None

In [ ]:
import pandas as pd
import time

expanded_queries = []

for _, row in queries_df.iterrows():

    query_id = str(row["query_id"])
    query = row["query_text"]

    try:
        expanded_query = expand_query(query)

        expanded_queries.append({
            "query_id": query_id,
            "original_query": query,
            "expanded_query": expanded_query
        })

        print(f"Done: {query_id}")
        pd.DataFrame(expanded_queries).to_csv(
            "scifact_gemini_expanded_queries.csv",
            index=False
        )
        time.sleep(1)

    except Exception as e:
        print(f"Error for query {query_id}: {e}")

In [41]:
pd.set_option('display.max_colwidth', None)

In [42]:
expanded_queries_df = pd.read_csv(
    "scifact_gemini_expanded_queries.csv",
    dtype={"query_id": str}
)

print(expanded_queries_df.shape)
expanded_queries_df

(300, 3)

,query_id,original_query,expanded_query
0,1,0-dimensional biomaterials show inductive properties.,"zero-dimensional biomaterials, 0D biomaterials, 0D biocompatible materials, inductive capacity, bioinductive potential, inductive behavior, bioinduction capabilities"
1,3,"1,000 genomes project enables mapping of genetic sequence variation consisting of rare variants with larger penetrance effects than common variants.","1KGP, 1000 Genomes, genomic sequence variation, rare genetic variants, high-penetrance alleles, common genetic variants, sequence polymorphisms"
2,5,1/2000 in UK have abnormal PrP positivity.,"abnormal prion protein prevalence United Kingdom, PrPSc carrier rate UK, prevalence of disease-associated prion protein, subclinical prion infection prevalence UK, abnormal PrP positivity rate Great Britain"
3,13,5% of perinatal mortality is due to low birth weight.,"perinatal death, perinatal demise, low birthweight, LBW, five percent, attributable to low birth weight, caused by low birth weight"
4,36,A deficiency of vitamin B12 increases blood levels of homocysteine.,"cobalamin deficiency, hypocobalaminemia, hyperhomocysteinemia, elevated plasma homocysteine, elevated serum homocysteine, vitamin B-12 deficiency"
...,...,...,...
295,1379,Women with a higher birth weight are more likely to develop breast cancer later in life.,"neonatal weight, birth mass, female breast carcinoma, mammary gland cancer, birth size"
296,1382,aPKCz causes tumour enhancement by affecting glutamine metabolism.,"PRKCZ, atypical protein kinase C zeta, tumor progression, neoplastic growth, glutaminolysis"
297,1385,cSMAC formation enhances weak ligand signalling.,"central supramolecular activation cluster, central supramolecular activation complex, immunological synapse, T-cell receptor signaling, TCR signaling"
298,1389,mTORC2 regulates intracellular cysteine levels through xCT inhibition.,"mammalian target of rapamycin complex 2, mechanistic target of rapamycin complex 2, SLC7A11, cystine-glutamate antiporter, intracellular cysteine, amino acid metabolism"
299,1395,p16INK4A accumulation is linked to an abnormal wound response caused by the microinvasive step of advanced Oral Potentially Malignant Lesions (OPMLs).,"CDKN2A, p16, multiple tumor suppressor 1, oral potentially malignant disorders, OPMDs, wound healing response"

In [43]:
doc_ids = corpus_df["index"].tolist()

q′ = Original Query + LLM Expansion

In [46]:
def add_punc(text):
    if not text.endswith("."):
        return text + '.'
    return text

In [47]:
expanded_queries_df['llm_output'] = expanded_queries_df['expanded_query']

In [48]:
expanded_queries_df['expanded_query'] = expanded_queries_df['original_query'].apply(add_punc) + " " + expanded_queries_df['llm_output']

In [49]:
expanded_queries_df

,query_id,original_query,expanded_query,llm_output
0,1,0-dimensional biomaterials show inductive properties.,"0-dimensional biomaterials show inductive properties. zero-dimensional biomaterials, 0D biomaterials, 0D biocompatible materials, inductive capacity, bioinductive potential, inductive behavior, bioinduction capabilities","zero-dimensional biomaterials, 0D biomaterials, 0D biocompatible materials, inductive capacity, bioinductive potential, inductive behavior, bioinduction capabilities"
1,3,"1,000 genomes project enables mapping of genetic sequence variation consisting of rare variants with larger penetrance effects than common variants.","1,000 genomes project enables mapping of genetic sequence variation consisting of rare variants with larger penetrance effects than common variants. 1KGP, 1000 Genomes, genomic sequence variation, rare genetic variants, high-penetrance alleles, common genetic variants, sequence polymorphisms","1KGP, 1000 Genomes, genomic sequence variation, rare genetic variants, high-penetrance alleles, common genetic variants, sequence polymorphisms"
2,5,1/2000 in UK have abnormal PrP positivity.,"1/2000 in UK have abnormal PrP positivity. abnormal prion protein prevalence United Kingdom, PrPSc carrier rate UK, prevalence of disease-associated prion protein, subclinical prion infection prevalence UK, abnormal PrP positivity rate Great Britain","abnormal prion protein prevalence United Kingdom, PrPSc carrier rate UK, prevalence of disease-associated prion protein, subclinical prion infection prevalence UK, abnormal PrP positivity rate Great Britain"
3,13,5% of perinatal mortality is due to low birth weight.,"5% of perinatal mortality is due to low birth weight. perinatal death, perinatal demise, low birthweight, LBW, five percent, attributable to low birth weight, caused by low birth weight","perinatal death, perinatal demise, low birthweight, LBW, five percent, attributable to low birth weight, caused by low birth weight"
4,36,A deficiency of vitamin B12 increases blood levels of homocysteine.,"A deficiency of vitamin B12 increases blood levels of homocysteine. cobalamin deficiency, hypocobalaminemia, hyperhomocysteinemia, elevated plasma homocysteine, elevated serum homocysteine, vitamin B-12 deficiency","cobalamin deficiency, hypocobalaminemia, hyperhomocysteinemia, elevated plasma homocysteine, elevated serum homocysteine, vitamin B-12 deficiency"
...,...,...,...,...
295,1379,Women with a higher birth weight are more likely to develop breast cancer later in life.,"Women with a higher birth weight are more likely to develop breast cancer later in life. neonatal weight, birth mass, female breast carcinoma, mammary gland cancer, birth size","neonatal weight, birth mass, female breast carcinoma, mammary gland cancer, birth size"
296,1382,aPKCz causes tumour enhancement by affecting glutamine metabolism.,"aPKCz causes tumour enhancement by affecting glutamine metabolism. PRKCZ, atypical protein kinase C zeta, tumor progression, neoplastic growth, glutaminolysis","PRKCZ, atypical protein kinase C zeta, tumor progression, neoplastic growth, glutaminolysis"
297,1385,cSMAC formation enhances weak ligand signalling.,"cSMAC formation enhances weak ligand signalling. central supramolecular activation cluster, central supramolecular activation complex, immunological synapse, T-cell receptor signaling, TCR signaling","central supramolecular activation cluster, central supramolecular activation complex, immunological synapse, T-cell receptor signaling, TCR signaling"
298,1389,mTORC2 regulates intracellular cysteine levels through xCT inhibition.,"mTORC2 regulates intracellular cysteine levels through xCT inhibition. mammalian target of rapamycin complex 2, mechanistic target of rapamycin complex 2, SLC7A11, cystine-glutamate antiporter, intracellular cysteine, amino acid metabolism","mammalian target of rapamycin complex 2, mechanistic target of rapamycin complex 2, SLC7A11, cystine-glutamate antiporter, intracellular cysteine, amino acid metabolism"
299,1395,p16INK4A accumulation is linked to an abnormal wound response caused by the microinvasive step of advanced Oral Potentially Malignant Lesions (OPMLs).,"p16INK4A accumulation is linked to an abnormal wound response caused by the microinvasive step of advanced Oral Potentially Malignant Lesions (OPMLs). CDKN2A, p16, multiple tumor suppressor 1, oral potentially malignant disorders, OPMDs, wound healing response","CDKN2A, p16, multiple tumor suppressor 1, oral potentially malignant disorders, OPMDs, wound healing response"

# Expanded Queries embedding and Retrieval

In [50]:
def embed_query(query):
    expquery_embedding = embedding_model.encode(
        query,
        show_progress_bar=True,
        normalize_embeddings=True
    )
    return expquery_embedding.reshape(1, -1)

In [51]:
def retrieve_docs_for_expanded():
    expanded_dict = {}
    for i, row in expanded_queries_df.iterrows():
        expanded_embedding = embed_query(row['expanded_query'])
        scores, indices = index.search(
        expanded_embedding,
        k=10 )
        docs_list = []
        
        for rank, idx in enumerate(indices[0], start=1):
            doc_info = {
                'rank': rank,
                'score': scores[0][rank - 1],
                'doc_id': corpus_df.iloc[idx]["index"]
            }
            docs_list.append(doc_info)
        
        expanded_dict[row['query_id']] = docs_list    
    return expanded_dict
expanded_dict = retrieve_docs_for_expanded()

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.34it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.64it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.80it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.11it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.76it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.63it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.58it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.62it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.53it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.28it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.04it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.04it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.52it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.60it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.20it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.76it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.13it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.17it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.49it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.62it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.46it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.85it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.26it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.19it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.26it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.17it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.04it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.34it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.80it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.76it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.46it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.58it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.90it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.40it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.49it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.71it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.00it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.99it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.53it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.80it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.06it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.49it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.90it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.11it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.63it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.87it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.19it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.70it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.33it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.25it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.51it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.62it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.85it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.14it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.26it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.33it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.33it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.69it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.45it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.99it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.20it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.94it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.35it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.87it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.31it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.75it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.80it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.30it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.64it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.50it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.31it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.31it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.90it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.09it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.62it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.99it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.75it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.30it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.24it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.17it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.20it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.35it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.24it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.40it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.20it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.38it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.99it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.62it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.93it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.26it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.90it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.05it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.58it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.43it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.25it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.47it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.81it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.74it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.10it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.81it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.99it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.90it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.95it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.26it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.94it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.43it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.43it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.07it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.62it/s]
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.06it/s]

In [59]:
expanded_dict

{'1': [{'rank': 1, 'score': np.float32(0.6278426), 'doc_id': '4346436'},
  {'rank': 2, 'score': np.float32(0.62767667), 'doc_id': '14103509'},
  {'rank': 3, 'score': np.float32(0.62335634), 'doc_id': '7583104'},
  {'rank': 4, 'score': np.float32(0.6228492), 'doc_id': '169264'},
  {'rank': 5, 'score': np.float32(0.6212362), 'doc_id': '23763738'},
  {'rank': 6, 'score': np.float32(0.6111123), 'doc_id': '84379954'},
  {'rank': 7, 'score': np.float32(0.6092697), 'doc_id': '10982689'},
  {'rank': 8, 'score': np.float32(0.6080052), 'doc_id': '35621259'},
  {'rank': 9, 'score': np.float32(0.6037443), 'doc_id': '21439293'},
  {'rank': 10, 'score': np.float32(0.60260206), 'doc_id': '29638116'}],
 '3': [{'rank': 1, 'score': np.float32(0.7234179), 'doc_id': '19058822'},
  {'rank': 2, 'score': np.float32(0.711523), 'doc_id': '10944947'},
  {'rank': 3, 'score': np.float32(0.69599354), 'doc_id': '23389795'},
  {'rank': 4, 'score': np.float32(0.6951089), 'doc_id': '2739854'},
  {'rank': 5, 'score': np.float32(0.68855125), 'doc_id': '45200347'},
  {'rank': 6, 'score': np.float32(0.6862878), 'doc_id': '1388704'},
  {'rank': 7, 'score': np.float32(0.68328583), 'doc_id': '13914198'},
  {'rank': 8, 'score': np.float32(0.68312275), 'doc_id': '4632921'},
  {'rank': 9, 'score': np.float32(0.6817311), 'doc_id': '4414547'},
  {'rank': 10, 'score': np.float32(0.68152523), 'doc_id': '10145528'}],
 '5': [{'rank': 1, 'score': np.float32(0.7952664), 'doc_id': '13734012'},
  {'rank': 2, 'score': np.float32(0.7723312), 'doc_id': '27063470'},
  {'rank': 3, 'score': np.float32(0.72013295), 'doc_id': '18617259'},
  {'rank': 4, 'score': np.float32(0.709407), 'doc_id': '1583041'},
  {'rank': 5, 'score': np.float32(0.7067764), 'doc_id': '42240424'},
  {'rank': 6, 'score': np.float32(0.70661366), 'doc_id': '23124332'},
  {'rank': 7, 'score': np.float32(0.70241976), 'doc_id': '21550246'},
  {'rank': 8, 'score': np.float32(0.6931499), 'doc_id': '11349166'},
  {'rank': 9, 'score': np.float32(0.6836157), 'doc_id': '25261168'},
  {'rank': 10, 'score': np.float32(0.67773527), 'doc_id': '1292369'}],
 '13': [{'rank': 1, 'score': np.float32(0.70820045), 'doc_id': '7662395'},
  {'rank': 2, 'score': np.float32(0.694472), 'doc_id': '1263446'},
  {'rank': 3, 'score': np.float32(0.6849652), 'doc_id': '26611834'},
  {'rank': 4, 'score': np.float32(0.6764401), 'doc_id': '16204011'},
  {'rank': 5, 'score': np.float32(0.6747873), 'doc_id': '4791384'},
  {'rank': 6, 'score': np.float32(0.67377114), 'doc_id': '16322674'},
  {'rank': 7, 'score': np.float32(0.6717491), 'doc_id': '30786800'},
  {'rank': 8, 'score': np.float32(0.66612), 'doc_id': '13791044'},
  {'rank': 9, 'score': np.float32(0.6660906), 'doc_id': '8529693'},
  {'rank': 10, 'score': np.float32(0.65994126), 'doc_id': '27123743'}],
 '36': [{'rank': 1, 'score': np.float32(0.7633296), 'doc_id': '18557974'},
  {'rank': 2, 'score': np.float32(0.74246454), 'doc_id': '37424881'},
  {'rank': 3, 'score': np.float32(0.74172235), 'doc_id': '11705328'},
  {'rank': 4, 'score': np.float32(0.7294228), 'doc_id': '21636085'},
  {'rank': 5, 'score': np.float32(0.7292909), 'doc_id': '33409100'},
  {'rank': 6, 'score': np.float32(0.7276572), 'doc_id': '3215494'},
  {'rank': 7, 'score': np.float32(0.7222549), 'doc_id': '13801259'},
  {'rank': 8, 'score': np.float32(0.7165895), 'doc_id': '10557471'},
  {'rank': 9, 'score': np.float32(0.7147208), 'doc_id': '18256197'},
  {'rank': 10, 'score': np.float32(0.71309996), 'doc_id': '16252863'}],
 '42': [{'rank': 1, 'score': np.float32(0.839033), 'doc_id': '18174210'},
  {'rank': 2, 'score': np.float32(0.80664015), 'doc_id': '27889071'},
  {'rank': 3, 'score': np.float32(0.78531367), 'doc_id': '40913091'},
  {'rank': 4, 'score': np.float32(0.7298447), 'doc_id': '32481310'},
  {'rank': 5, 'score': np.float32(0.72059417), 'doc_id': '1145473'},
  {'rank': 6, 'score': np.float32(0.72002506), 'doc_id': '45218443'},
  {'rank': 7, 'score': np.float32(0.71565473), 'doc_id': '24042919'},
  {'rank': 8, 'score': np.float32(0.7115966), 'doc_id': '9254550'},
  {'rank': 9, 'score': np.float32(0.70468295), 'doc_id': '13959707'},
  {'rank': 10, 'score': np.float32(0.68959284), 'doc_id': '6315132'}],
 '48': [{'rank': 1, 'score': np.float32(0.8174025), 'doc_id': '27063470'},
  {'rank': 2, 'score': np.float32(0.8053552), 'doc_id': '11349166'},
  {'rank': 3, 'score': np.float32(0.76635426), 'doc_id': '18617259'},
  {'rank': 4, 'score': np.float32(0.76384604), 'doc_id': '23203102'},
  {'rank': 5, 'score': np.float32(0.7550672), 'doc_id': '13734012'},
  {'rank': 6, 'score': np.float32(0.69308585), 'doc_id': '3078080'},
  {'rank': 7, 'score': np.float32(0.688957), 'doc_id': '29955650'},
  {'rank': 8, 'score': np.float32(0.68842816), 'doc_id': '25261168'},
  {'rank': 9, 'score': np.float32(0.68054754), 'doc_id': '3413083'},
  {'rank': 10, 'score': np.float32(0.676558), 'doc_id': '5850219'}],
 '49': [{'rank': 1, 'score': np.float32(0.9055123), 'doc_id': '5953485'},
  {'rank': 2, 'score': np.float32(0.796909), 'doc_id': '5702790'},
  {'rank': 3, 'score': np.float32(0.7890524), 'doc_id': '7029990'},
  {'rank': 4, 'score': np.float32(0.73501587), 'doc_id': '23913146'},
  {'rank': 5, 'score': np.float32(0.7288204), 'doc_id': '29107180'},
  {'rank': 6, 'score': np.float32(0.72335), 'doc_id': '12652963'},
  {'rank': 7, 'score': np.float32(0.71326774), 'doc_id': '950306'},
  {'rank': 8, 'score': np.float32(0.71299064), 'doc_id': '8006440'},
  {'rank': 9, 'score': np.float32(0.70886517), 'doc_id': '35448676'},
  {'rank': 10, 'score': np.float32(0.7010385), 'doc_id': '22362025'}],
 '50': [{'rank': 1, 'score': np.float32(0.8091901), 'doc_id': '12580014'},
  {'rank': 2, 'score': np.float32(0.7734555), 'doc_id': '18488986'},
  {'rank': 3, 'score': np.float32(0.76946914), 'doc_id': '25738896'},
  {'rank': 4, 'score': np.float32(0.7670232), 'doc_id': '39559521'},
  {'rank': 5, 'score': np.float32(0.7565855), 'doc_id': '13989491'},
  {'rank': 6, 'score': np.float32(0.7463958), 'doc_id': '15405204'},
  {'rank': 7, 'score': np.float32(0.7194309), 'doc_id': '8354687'},
  {'rank': 8, 'score': np.float32(0.71914434), 'doc_id': '29785642'},
  {'rank': 9, 'score': np.float32(0.70124155), 'doc_id': '4561402'},
  {'rank': 10, 'score': np.float32(0.68995), 'doc_id': '36950726'}],
 '51': [{'rank': 1, 'score': np.float32(0.82762545), 'doc_id': '45638119'},
  {'rank': 2, 'score': np.float32(0.699662), 'doc_id': '3067015'},
  {'rank': 3, 'score': np.float32(0.6890811), 'doc_id': '24349992'},
  {'rank': 4, 'score': np.float32(0.68902206), 'doc_id': '8963413'},
  {'rank': 5, 'score': np.float32(0.68876094), 'doc_id': '21181273'},
  {'rank': 6, 'score': np.float32(0.6850995), 'doc_id': '1866911'},
  {'rank': 7, 'score': np.float32(0.68466806), 'doc_id': '12762485'},
  {'rank': 8, 'score': np.float32(0.68419534), 'doc_id': '14180565'},
  {'rank': 9, 'score': np.float32(0.68312055), 'doc_id': '23830488'},
  {'rank': 10, 'score': np.float32(0.6808895), 'doc_id': '4886637'}],
 '53': [{'rank': 1, 'score': np.float32(0.82666004), 'doc_id': '45638119'},
  {'rank': 2, 'score': np.float32(0.71137255), 'doc_id': '8963413'},
  {'rank': 3, 'score': np.float32(0.70537084), 'doc_id': '21181273'},
  {'rank': 4, 'score': np.float32(0.6948345), 'doc_id': '3067015'},
  {'rank': 5, 'score': np.float32(0.6947415), 'doc_id': '12762485'},
  {'rank': 6, 'score': np.float32(0.68979883), 'doc_id': '20886584'},
  {'rank': 7, 'score': np.float32(0.6883218), 'doc_id': '24349992'},
  {'rank': 8, 'score': np.float32(0.6871824), 'doc_id': '14180565'},
  {'rank': 9, 'score': np.float32(0.68679106), 'doc_id': '2389574'},
  {'rank': 10, 'score': np.float32(0.6848006), 'doc_id': '4886637'}],
 '54': [{'rank': 1, 'score': np.float32(0.83570695), 'doc_id': '49556906'},
  {'rank': 2, 'score': np.float32(0.7766646), 'doc_id': '3973445'},
  {'rank': 3, 'score': np.float32(0.77103347), 'doc_id': '9899292'},
  {'rank': 4, 'score': np.float32(0.7596036), 'doc_id': '24721866'},
  {'rank': 5, 'score': np.float32(0.75687253), 'doc_id': '3419709'},
  {'rank': 6, 'score': np.float32(0.7546512), 'doc_id': '1590744'},
  {'rank': 7, 'score': np.float32(0.75381595), 'doc_id': '7005276'},
  {'rank': 8, 'score': np.float32(0.7513034), 'doc_id': '26025820'},
  {'rank': 9, 'score': np.float32(0.7478666), 'doc_id': '32408470'},
  {'rank': 10, 'score': np.float32(0.74153256), 'doc_id': '22036571'}],
 '56': [{'rank': 1, 'score': np.float32(0.8724196), 'doc_id': '4709641'},
  {'rank': 2, 'score': np.float32(0.7918799), 'doc_id': '13814480'},
  {'rank': 3, 'score': np.float32(0.7815336), 'doc_id': '10795063'},
  {'rank': 4, 'score': np.float32(0.78103995), 'doc_id': '4459491'},
  {'rank': 5, 'score': np.float32(0.76583725), 'doc_id': '30351165'},
  {'rank': 6, 'score': np.float32(0.75843275), 'doc_id': '8892905'},
  {'rank': 7, 'score': np.float32(0.751042), 'doc_id': '11659421'},
  {'rank': 8, 'score': np.float32(0.73972386), 'doc_id': '51386222'},
  {'rank': 9, 'score': np.float32(0.7393016), 'doc_id': '9194077'},
  {'rank': 10, 'score': np.float32(0.7379713), 'doc_id': '4407385'}],
 '57': [{'rank': 1, 'score': np.float32(0.8732174), 'doc_id': '4709641'},
  {'rank': 2, 'score': np.float32(0.7943001), 'doc_id': '13814480'},
  {'rank': 3, 'score': np.float32(0.7842879), 'doc_id': '4459491'},
  {'rank': 4, 'score': np.float32(0.77984095), 'doc_id': '10795063'},
  {'rank': 5, 'score': np.float32(0.7685549), 'doc_id': '30351165'},
  {'rank': 6, 'score': np.float32(0.75293446), 'doc_id': '11659421'},
  {'rank': 7, 'score': np.float32(0.7468931), 'doc_id': '8892905'},
  {'rank': 8, 'score': np.float32(0.7395506), 'doc_id': '4407385'},
  {'rank': 9, 'score': np.float32(0.73933446), 'doc_id': '13293033'},
  {'rank': 10, 'score': np.float32(0.7387103), 'doc_id': '19970015'}],
 '70': [{'rank': 1, 'score': np.float32(0.78980994), 'doc_id': '5254463'},
  {'rank': 2, 'score': np.float32(0.74107754), 'doc_id': '11903247'},
  {'rank': 3, 'score': np.float32(0.74032855), 'doc_id': '36464673'},
  {'rank': 4, 'score': np.float32(0.73639905), 'doc_id': '4414547'},
  {'rank': 5, 'score': np.float32(0.7327783), 'doc_id': '9483851'},
  {'rank': 6, 'score': np.float32(0.73020816), 'doc_id': '31624828'},
  {'rank': 7, 'score': np.float32(0.7301229), 'doc_id': '42489926'},
  {'rank': 8, 'score': np.float32(0.7283466), 'doc_id': '35684881'},
  {'rank': 9, 'score': np.float32(0.726759), 'doc_id': '21557055'},
  {'rank': 10, 'score': np.float32(0.72661567), 'doc_id': '9169645'}],
 '72': [{'rank': 1, 'score': np.float32(0.7601601), 'doc_id': '1031534'},
  {'rank': 2, 'score': np.float32(0.7557293), 'doc_id': '6076903'},
  {'rank': 3, 'score': np.float32(0.73377806), 'doc_id': '14492964'},
  {'rank': 4, 'score': np.float32(0.7180306), 'doc_id': '39291138'},
  {'rank': 5, 'score': np.float32(0.7015512), 'doc_id': '40383969'},
  {'rank': 6, 'score': np.float32(0.6929666), 'doc_id': '2119889'},
  {'rank': 7, 'score': np.float32(0.6875397), 'doc_id': '8997410'},
  {'rank': 8, 'score': np.float32(0.68513286), 'doc_id': '27569370'},
  {'rank': 9, 'score': np.float32(0.68102556), 'doc_id': '17119869'},
  {'rank': 10, 'score': np.float32(0.6806452), 'doc_id': '14105446'}],
 '75': [{'rank': 1, 'score': np.float32(0.7958994), 'doc_id': '4387784'},
  {'rank': 2, 'score': np.float32(0.74875844), 'doc_id': '25657127'},
  {'rank': 3, 'score': np.float32(0.7289705), 'doc_id': '37768883'},
  {'rank': 4, 'score': np.float32(0.7263541), 'doc_id': '36233757'},
  {'rank': 5, 'score': np.float32(0.7195853), 'doc_id': '29214508'},
  {'rank': 6, 'score': np.float32(0.7110716), 'doc_id': '38805486'},
  {'rank': 7, 'score': np.float32(0.6968488), 'doc_id': '1744752'},
  {'rank': 8, 'score': np.float32(0.6913588), 'doc_id': '13965483'},
  {'rank': 9, 'score': np.float32(0.68601894), 'doc_id': '26488879'},
  {'rank': 10, 'score': np.float32(0.6825496), 'doc_id': '41900731'}],
 '94': [{'rank': 1, 'score': np.float32(0.6614777), 'doc_id': '18025240'},
  {'rank': 2, 'score': np.float32(0.65680665), 'doc_id': '12409683'},
  {'rank': 3, 'score': np.float32(0.63858557), 'doc_id': '10617916'},
  {'rank': 4, 'score': np.float32(0.6155604), 'doc_id': '1805641'},
  {'rank': 5, 'score': np.float32(0.6066741), 'doc_id': '3929361'},
  {'rank': 6, 'score': np.float32(0.5989348), 'doc_id': '13966946'},
  {'rank': 7, 'score': np.float32(0.59478205), 'doc_id': '1215116'},
  {'rank': 8, 'score': np.float32(0.5894446), 'doc_id': '7552215'},
  {'rank': 9, 'score': np.float32(0.58888674), 'doc_id': '15237660'},
  {'rank': 10, 'score': np.float32(0.58385503), 'doc_id': '26045237'}],
 '99': [{'rank': 1, 'score': np.float32(0.70554924), 'doc_id': '18810195'},
  {'rank': 2, 'score': np.float32(0.6806811), 'doc_id': '36233757'},
  {'rank': 3, 'score': np.float32(0.676456), 'doc_id': '25657127'},
  {'rank': 4, 'score': np.float32(0.6658404), 'doc_id': '12265561'},
  {'rank': 5, 'score': np.float32(0.6646439), 'doc_id': '4387784'},
  {'rank': 6, 'score': np.float32(0.66260237), 'doc_id': '14180217'},
  {'rank': 7, 'score': np.float32(0.6619089), 'doc_id': '30543439'},
  {'rank': 8, 'score': np.float32(0.66155994), 'doc_id': '41900731'},
  {'rank': 9, 'score': np.float32(0.66147864), 'doc_id': '13578199'},
  {'rank': 10, 'score': np.float32(0.6603589), 'doc_id': '2119889'}],
 '100': [{'rank': 1, 'score': np.float32(0.7911801), 'doc_id': '4381486'},
  {'rank': 2, 'score': np.float32(0.7644756), 'doc_id': '14550841'},
  {'rank': 3, 'score': np.float32(0.73665076), 'doc_id': '13980338'},
  {'rank': 4, 'score': np.float32(0.73409337), 'doc_id': '25516011'},
  {'rank': 5, 'score': np.float32(0.73349667), 'doc_id': '11020675'},
  {'rank': 6, 'score': np.float32(0.7266047), 'doc_id': '13116880'},
  {'rank': 7, 'score': np.float32(0.7264286), 'doc_id': '92499'},
  {'rank': 8, 'score': np.float32(0.71893567), 'doc_id': '4421787'},
  {'rank': 9, 'score': np.float32(0.7104745), 'doc_id': '9154703'},
  {'rank': 10, 'score': np.float32(0.70889986), 'doc_id': '18374364'}],
 '113': [{'rank': 1, 'score': np.float32(0.78884935), 'doc_id': '6157837'},
  {'rank': 2, 'score': np.float32(0.75954497), 'doc_id': '25816994'},
  {'rank': 3, 'score': np.float32(0.727008), 'doc_id': '14584755'},
  {'rank': 4, 'score': np.float32(0.72370803), 'doc_id': '4678846'},
  {'rank': 5, 'score': np.float32(0.7235839), 'doc_id': '1759213'},
  {'rank': 6, 'score': np.float32(0.7180947), 'doc_id': '44030361'},
  {'rank': 7, 'score': np.float32(0.70817494), 'doc_id': '40790033'},
  {'rank': 8, 'score': np.float32(0.7066521), 'doc_id': '140098548'},
  {'rank': 9, 'score': np.float32(0.70212024), 'doc_id': '3825750'},
  {'rank': 10, 'score': np.float32(0.69817466), 'doc_id': '26199970'}],
 '115': [{'rank': 1, 'score': np.float32(0.77455115), 'doc_id': '33872649'},
  {'rank': 2, 'score': np.float32(0.63013875), 'doc_id': '15879544'},
  {'rank': 3, 'score': np.float32(0.59211355), 'doc_id': '695938'},
  {'rank': 4, 'score': np.float32(0.5914154), 'doc_id': '4942718'},
  {'rank': 5, 'score': np.float32(0.59077895), 'doc_id': '16787954'},
  {'rank': 6, 'score': np.float32(0.5903312), 'doc_id': '38043606'},
  {'rank': 7, 'score': np.float32(0.5856212), 'doc_id': '24746892'},
  {'rank': 8, 'score': np.float32(0.5848105), 'doc_id': '15414628'},
  {'rank': 9, 'score': np.float32(0.5844214), 'doc_id': '1103795'},
  {'rank': 10, 'score': np.float32(0.5843402), 'doc_id': '12881593'}],
 '118': [{'rank': 1, 'score': np.float32(0.82986003), 'doc_id': '4465735'},
  {'rank': 2, 'score': np.float32(0.82884574), 'doc_id': '6372244'},
  {'rank': 3, 'score': np.float32(0.71867776), 'doc_id': '15578265'},
  {'rank': 4, 'score': np.float32(0.715163), 'doc_id': '32454714'},
  {'rank': 5, 'score': np.float32(0.712504), 'doc_id': '52805891'},
  {'rank': 6, 'score': np.float32(0.7077894), 'doc_id': '21956124'},
  {'rank': 7, 'score': np.float32(0.7027217), 'doc_id': '4492358'},
  {'rank': 8, 'score': np.float32(0.690436), 'doc_id': '2604063'},
  {'rank': 9, 'score': np.float32(0.6830131), 'doc_id': '15274349'},
  {'rank': 10, 'score': np.float32(0.6819081), 'doc_id': '34603465'}],
 '124': [{'rank': 1, 'score': np.float32(0.83531713), 'doc_id': '4883040'},
  {'rank': 2, 'score': np.float32(0.81847644), 'doc_id': '7111021'},
  {'rank': 3, 'score': np.float32(0.78104955), 'doc_id': '31363207'},
  {'rank': 4, 'score': np.float32(0.76965535), 'doc_id': '21479231'},
  {'rank': 5, 'score': np.float32(0.7586294), 'doc_id': '13899137'},
  {'rank': 6, 'score': np.float32(0.72963405), 'doc_id': '14319754'},
  {'rank': 7, 'score': np.float32(0.7224153), 'doc_id': '32012666'},
  {'rank': 8, 'score': np.float32(0.7201631), 'doc_id': '22414304'},
  {'rank': 9, 'score': np.float32(0.7182462), 'doc_id': '1986482'},
  {'rank': 10, 'score': np.float32(0.7156012), 'doc_id': '13914633'}],
 '127': [{'rank': 1, 'score': np.float32(0.7129988), 'doc_id': '35231675'},
  {'rank': 2, 'score': np.float32(0.70905334), 'doc_id': '21598000'},
  {'rank': 3, 'score': np.float32(0.68344295), 'doc_id': '10423989'},
  {'rank': 4, 'score': np.float32(0.67678595), 'doc_id': '12685434'},
  {'rank': 5, 'score': np.float32(0.6762432), 'doc_id': '38623601'},
  {'rank': 6, 'score': np.float32(0.6742183), 'doc_id': '11181416'},
  {'rank': 7, 'score': np.float32(0.67394125), 'doc_id': '11048759'},
  {'rank': 8, 'score': np.float32(0.6727814), 'doc_id': '22937651'},
  {'rank': 9, 'score': np.float32(0.6709138), 'doc_id': '39863735'},
  {'rank': 10, 'score': np.float32(0.6691346), 'doc_id': '26495128'}],
 '128': [{'rank': 1, 'score': np.float32(0.6605395), 'doc_id': '12549585'},
  {'rank': 2, 'score': np.float32(0.6410864), 'doc_id': '25175997'},
  {'rank': 3, 'score': np.float32(0.6372516), 'doc_id': '79447'},
  {'rank': 4, 'score': np.float32(0.6370419), 'doc_id': '23513718'},
  {'rank': 5, 'score': np.float32(0.6362787), 'doc_id': '25300664'},
  {'rank': 6, 'score': np.float32(0.6324507), 'doc_id': '22889972'},
  {'rank': 7, 'score': np.float32(0.63076675), 'doc_id': '9310407'},
  {'rank': 8, 'score': np.float32(0.630219), 'doc_id': '2056197'},
  {'rank': 9, 'score': np.float32(0.62969077), 'doc_id': '12513972'},
  {'rank': 10, 'score': np.float32(0.6278704), 'doc_id': '9288638'}],
 '129': [{'rank': 1, 'score': np.float32(0.7720653), 'doc_id': '27768226'},
  {'rank': 2, 'score': np.float32(0.641433), 'doc_id': '6477536'},
  {'rank': 3, 'score': np.float32(0.63677764), 'doc_id': '16979690'},
  {'rank': 4, 'score': np.float32(0.60067725), 'doc_id': '7547329'},
  {'rank': 5, 'score': np.float32(0.5985402), 'doc_id': '39652608'},
  {'rank': 6, 'score': np.float32(0.59396243), 'doc_id': '790598'},
  {'rank': 7, 'score': np.float32(0.59386575), 'doc_id': '4688277'},
  {'rank': 8, 'score': np.float32(0.5920961), 'doc_id': '6319826'},
  {'rank': 9, 'score': np.float32(0.5888331), 'doc_id': '31495049'},
  {'rank': 10, 'score': np.float32(0.58332074), 'doc_id': '45920278'}],
 '130': [{'rank': 1, 'score': np.float32(0.77471894), 'doc_id': '27768226'},
  {'rank': 2, 'score': np.float32(0.61479473), 'doc_id': '16979690'},
  {'rank': 3, 'score': np.float32(0.6077471), 'doc_id': '6477536'},
  {'rank': 4, 'score': np.float32(0.5843199), 'doc_id': '39652608'},
  {'rank': 5, 'score': np.float32(0.58281446), 'doc_id': '790598'},
  {'rank': 6, 'score': np.float32(0.57791966), 'doc_id': '6319826'},
  {'rank': 7, 'score': np.float32(0.5751797), 'doc_id': '45920278'},
  {'rank': 8, 'score': np.float32(0.5688355), 'doc_id': '4688277'},
  {'rank': 9, 'score': np.float32(0.568516), 'doc_id': '26456326'},
  {'rank': 10, 'score': np.float32(0.5680858), 'doc_id': '22711954'}],
 '132': [{'rank': 1, 'score': np.float32(0.7205847), 'doc_id': '2443495'},
  {'rank': 2, 'score': np.float32(0.7135418), 'doc_id': '9159125'},
  {'rank': 3, 'score': np.float32(0.71230394), 'doc_id': '3866315'},
  {'rank': 4, 'score': np.float32(0.7113172), 'doc_id': '39903312'},
  {'rank': 5, 'score': np.float32(0.7000785), 'doc_id': '15648443'},
  {'rank': 6, 'score': np.float32(0.6991731), 'doc_id': '6945691'},

In [61]:
expanded_queries_df

,query_id,original_query,expanded_query,llm_output
0,1,0-dimensional biomaterials show inductive properties.,"0-dimensional biomaterials show inductive properties. zero-dimensional biomaterials, 0D biomaterials, 0D biocompatible materials, inductive capacity, bioinductive potential, inductive behavior, bioinduction capabilities","zero-dimensional biomaterials, 0D biomaterials, 0D biocompatible materials, inductive capacity, bioinductive potential, inductive behavior, bioinduction capabilities"
1,3,"1,000 genomes project enables mapping of genetic sequence variation consisting of rare variants with larger penetrance effects than common variants.","1,000 genomes project enables mapping of genetic sequence variation consisting of rare variants with larger penetrance effects than common variants. 1KGP, 1000 Genomes, genomic sequence variation, rare genetic variants, high-penetrance alleles, common genetic variants, sequence polymorphisms","1KGP, 1000 Genomes, genomic sequence variation, rare genetic variants, high-penetrance alleles, common genetic variants, sequence polymorphisms"
2,5,1/2000 in UK have abnormal PrP positivity.,"1/2000 in UK have abnormal PrP positivity. abnormal prion protein prevalence United Kingdom, PrPSc carrier rate UK, prevalence of disease-associated prion protein, subclinical prion infection prevalence UK, abnormal PrP positivity rate Great Britain","abnormal prion protein prevalence United Kingdom, PrPSc carrier rate UK, prevalence of disease-associated prion protein, subclinical prion infection prevalence UK, abnormal PrP positivity rate Great Britain"
3,13,5% of perinatal mortality is due to low birth weight.,"5% of perinatal mortality is due to low birth weight. perinatal death, perinatal demise, low birthweight, LBW, five percent, attributable to low birth weight, caused by low birth weight","perinatal death, perinatal demise, low birthweight, LBW, five percent, attributable to low birth weight, caused by low birth weight"
4,36,A deficiency of vitamin B12 increases blood levels of homocysteine.,"A deficiency of vitamin B12 increases blood levels of homocysteine. cobalamin deficiency, hypocobalaminemia, hyperhomocysteinemia, elevated plasma homocysteine, elevated serum homocysteine, vitamin B-12 deficiency","cobalamin deficiency, hypocobalaminemia, hyperhomocysteinemia, elevated plasma homocysteine, elevated serum homocysteine, vitamin B-12 deficiency"
...,...,...,...,...
295,1379,Women with a higher birth weight are more likely to develop breast cancer later in life.,"Women with a higher birth weight are more likely to develop breast cancer later in life. neonatal weight, birth mass, female breast carcinoma, mammary gland cancer, birth size","neonatal weight, birth mass, female breast carcinoma, mammary gland cancer, birth size"
296,1382,aPKCz causes tumour enhancement by affecting glutamine metabolism.,"aPKCz causes tumour enhancement by affecting glutamine metabolism. PRKCZ, atypical protein kinase C zeta, tumor progression, neoplastic growth, glutaminolysis","PRKCZ, atypical protein kinase C zeta, tumor progression, neoplastic growth, glutaminolysis"
297,1385,cSMAC formation enhances weak ligand signalling.,"cSMAC formation enhances weak ligand signalling. central supramolecular activation cluster, central supramolecular activation complex, immunological synapse, T-cell receptor signaling, TCR signaling","central supramolecular activation cluster, central supramolecular activation complex, immunological synapse, T-cell receptor signaling, TCR signaling"
298,1389,mTORC2 regulates intracellular cysteine levels through xCT inhibition.,"mTORC2 regulates intracellular cysteine levels through xCT inhibition. mammalian target of rapamycin complex 2, mechanistic target of rapamycin complex 2, SLC7A11, cystine-glutamate antiporter, intracellular cysteine, amino acid metabolism","mammalian target of rapamycin complex 2, mechanistic target of rapamycin complex 2, SLC7A11, cystine-glutamate antiporter, intracellular cysteine, amino acid metabolism"
299,1395,p16INK4A accumulation is linked to an abnormal wound response caused by the microinvasive step of advanced Oral Potentially Malignant Lesions (OPMLs).,"p16INK4A accumulation is linked to an abnormal wound response caused by the microinvasive step of advanced Oral Potentially Malignant Lesions (OPMLs). CDKN2A, p16, multiple tumor suppressor 1, oral potentially malignant disorders, OPMDs, wound healing response","CDKN2A, p16, multiple tumor suppressor 1, oral potentially malignant disorders, OPMDs, wound healing response"

In [62]:
exp_run_dict = {}

for i, row in expanded_queries_df.iterrows():
    query_id = row['query_id']  
    query_txt = row['expanded_query']
    
    # Get embeddings and search
    query_embedding = embedding_model.encode(
        [query_txt],
        normalize_embeddings=True
    )
    scores, indices = index.search(query_embedding, k=10)
    
    doc_scores = {}
    for rank, idx in enumerate(indices[0], start=1): 
        doc_id = corpus_df.iloc[idx]["index"]
        score = scores[0][rank - 1]
        doc_scores[doc_id] = float(score)  
    
    exp_run_dict[query_id] = doc_scores

In [63]:
from ranx import Qrels, Run, evaluate

results = evaluate(
    qrels,
    exp_run_dict,
    [
        "recall@5",
        "recall@10",
        "mrr@10",
        "ndcg@10"
    ]
)

In [64]:
results

{'recall@5': np.float64(0.8195555555555556),
 'recall@10': np.float64(0.8752222222222222),
 'mrr@10': np.float64(0.6994616402116401),
 'ndcg@10': np.float64(0.7379842613113202)}

In [65]:
import pandas as pd
from ranx import Qrels, Run, evaluate

# Create Qrels and Run objects
qrels_obj = Qrels(qrels)
exp_run_obj = Run(exp_run_dict)

# Get overall results
overall_results = evaluate(
    qrels_obj,
    exp_run_obj,
    ["recall@5", "recall@10", "mrr@10", "ndcg@10"]
)

# Get per-query results by iterating over each query
per_query_results = {}

for query_id in qrels.keys():
    if query_id in exp_run_dict:
        # Create single-query Qrels and Run
        single_qrels = Qrels({query_id: qrels[query_id]})
        single_run = Run({query_id: exp_run_dict[query_id]})
        
        # Evaluate for this single query
        single_results = evaluate(
            single_qrels,
            single_run,
            ["recall@5", "recall@10", "mrr@10", "ndcg@10"]
        )
        
        per_query_results[query_id] = single_results

df_per_expquery = pd.DataFrame(per_query_results).T
df_per_expquery.index.name = 'query_id'
df_per_expquery = df_per_expquery.reset_index()

In [66]:
df_per_expquery

    query_id  recall@5  recall@10    mrr@10   ndcg@10
0          1       0.0        0.0  0.000000  0.000000
1          3       0.0        0.0  0.000000  0.000000
2          5       1.0        1.0  1.000000  1.000000
3         13       0.0        0.0  0.000000  0.000000
4         36       0.5        0.5  0.333333  0.306574
..       ...       ...        ...       ...       ...
295     1379       1.0        1.0  1.000000  0.982892
296     1382       1.0        1.0  1.000000  1.000000
297     1385       1.0        1.0  1.000000  1.000000
298     1389       1.0        1.0  1.000000  1.000000
299     1395       0.0        1.0  0.166667  0.356207

[300 rows x 5 columns]

In [67]:
df_per_query

    query_id  recall@5  recall@10    mrr@10   ndcg@10
0          1       0.0        0.0  0.000000  0.000000
1          3       1.0        1.0  0.200000  0.386853
2          5       1.0        1.0  1.000000  1.000000
3         13       0.0        1.0  0.166667  0.356207
4         36       0.5        0.5  0.250000  0.264068
..       ...       ...        ...       ...       ...
295     1379       1.0        1.0  1.000000  1.000000
296     1382       1.0        1.0  1.000000  1.000000
297     1385       1.0        1.0  1.000000  1.000000
298     1389       1.0        1.0  1.000000  1.000000
299     1395       1.0        1.0  0.333333  0.500000

[300 rows x 5 columns]